// AUTO-GENERATED by scripts/emit-champion-status.py - do not edit by hand.
// Time-boxed champion banners for the Sports nav + League Hub sidebar.
// Regenerated by run-workbook-sync.py after the league data builds.
export type ChampionBanner = { label: string; until: number };
export const CHAMPION_STATUS: Record<string, ChampionBanner> = {
  "/teams/nba": { label: "Knicks - NBA Champions", until: 1782172799000 },
  "/teams/nhl": { label: "Hurricanes - Stanley Cup Champions", until: 1782311020068 },
};
