// Maps a champions-history competition slug to the champions/honours section
// of an existing hub page (deep-linked via #anchor). The All-Time list on
// /sports/champions, the metro Championship History and the country
// Championship History all link through competitionHref(); mapped competitions
// route to their hub section instead of the generic /sports/champions/[comp]
// honour roll (those roll pages are no longer generated for mapped competitions).
// Competitions with no hub (Argentina Primera, Brasileiro, Liga MX, Mitropa
// Cup, Latin Cup, Frozen Four, women's Olympic basketball) keep their roll.
// Client-safe: pure data + string helpers, no server imports.

const COMP_TO_HUB: Record<string, string> = {
  "fifa-world-cup": "/teams/national/tournaments/world-cup#champions",
  "uefa-european-championship": "/teams/national/tournaments/euros#champions",
  "copa-america": "/teams/national/tournaments/copa-america#champions",
  "africa-cup-of-nations": "/teams/national/tournaments/afcon#champions",
  "afc-asian-cup": "/teams/national/tournaments/asian-cup#champions",
  "concacaf-championship-gold-cup": "/teams/national/tournaments/gold-cup#champions",
  "ofc-nations-cup": "/teams/national/tournaments/ofc-nations-cup#champions",
  "confederations-cup": "/teams/national/tournaments/intercontinental#champions",
  "champions-league": "/teams/football/tournaments/champions-league#finals",
  "europa-league": "/teams/football/tournaments/europa-league#finals",
  "europa-conference-league": "/teams/football/tournaments/conference-league#finals",
  "cup-winners-cup": "/teams/football/tournaments/cup-winners-cup#finals",
  "inter-cities-fairs-cup": "/teams/football/tournaments/inter-cities-fairs-cup#finals",
  "copa-libertadores": "/teams/football/tournaments/copa-libertadores#finals",
  "club-world-cup": "/teams/football/tournaments/club-world-cup#finals",
  "caf-champions-league": "/teams/football/tournaments/other-continental#finals",
  "afc-champions-league-elite": "/teams/football/tournaments/other-continental#finals",
  "concacaf-champions-cup": "/teams/football/tournaments/other-continental#finals",
  "ofc-champions-league": "/teams/football/tournaments/other-continental#finals",
  "premier-league": "/teams/football/leagues/premier-league#champions",
  "la-liga": "/teams/football/leagues/la-liga#champions",
  "serie-a": "/teams/football/leagues/serie-a#champions",
  "bundesliga": "/teams/football/leagues/bundesliga#champions",
  "ligue-1": "/teams/football/leagues/ligue-1#champions",
  "eredivisie": "/teams/football/leagues/eredivisie#champions",
  "primeira-liga": "/teams/football/leagues/primeira-liga#champions",
  "scottish-premiership": "/teams/football/leagues/scottish-premiership#champions",
  "major-league-soccer": "/teams/football/leagues/mls#honors",
  "fa-cup": "/teams/football/cups#fa-cup",
  "cricket-world-cup": "/teams/cricket#honours",
  "t20-world-cup": "/teams/cricket#honours",
  "world-test-championship": "/teams/cricket#wtc",
  "county-championship": "/teams/cricket/county#county",
  "ipl": "/teams/ipl#champions",
  "t20-blast": "/teams/cricket/t20#blast",
  "big-bash-league": "/teams/cricket/t20#bbl",
  "bpl": "/teams/cricket/t20#bpl",
  "cpl": "/teams/cricket/t20#cpl",
  "lanka-premier-league": "/teams/cricket/t20#lpl",
  "pakistan-super-league": "/teams/cricket/t20#psl",
  "sa20": "/teams/cricket/t20#sa20",
  "super-smash": "/teams/cricket/t20#smash",
  "the-hundred": "/teams/cricket/t20#hundred",
  "international-league-t20": "/teams/cricket/t20#ilt20",
  "mlb": "/teams/mlb#all-time",
  "japan-series": "/teams/baseball/npb#japan-series",
  "college-world-series": "/teams/baseball/college#champions",
  "world-baseball-classic": "/teams/baseball#champions",
  "nba": "/teams/nba#all-time",
  "euroleague": "/teams/basketball/euroleague#champions",
  "cba": "/teams/basketball/domestic#cba",
  "fiba-world-cup": "/teams/basketball#world-cup",
  "ncaa-champions": "/teams/cbb#champions",
  "olympic-mens-basketball": "/teams/basketball#olympics",
  "nhl": "/teams/nhl#all-time",
  "khl": "/teams/hockey/domestic#khl",
  "world-cup-of-hockey": "/teams/hockey#world-cup",
  "olympic-mens-hockey": "/teams/hockey#olympics",
  "nfl": "/teams/nfl#all-time",
  "college-football": "/teams/cfb#champions",
  "afl": "/teams/afl#finals",
  "nrl": "/teams/nrl#finals",
  "cfl": "/teams/cfl#finals",
  "rugby-league-world-cup": "/teams/rugby-league#champions",
  "rugby-world-cup": "/teams/rugby-union#world-cup",
  "six-nations-tournament": "/teams/rugby-union#six-nations",
  "champions-cup": "/teams/rugby-union/clubs#european",
  "top-14": "/teams/rugby-union/clubs#top14",
  "prem-rugby": "/teams/rugby-union/clubs#premiership",
  "masters-tournament": "/teams/golf#masters",
  "pga-championship": "/teams/golf#pga",
  "the-open-championship": "/teams/golf#the-open",
  "us-open-championship": "/teams/golf#us-open",
  "australian-open-mens": "/teams/tennis#australian",
  "australian-open-womens": "/teams/tennis#australian",
  "french-open-mens": "/teams/tennis#french",
  "french-open-womens": "/teams/tennis#french",
  "us-open-mens": "/teams/tennis#us-open",
  "us-open-womens": "/teams/tennis#us-open",
  "wimbledon-mens": "/teams/tennis#wimbledon",
  "wimbledon-womens": "/teams/tennis#wimbledon",
  "world-drivers-championship": "/teams/f1#champions",
  "ihf-world-championship": "/teams/handball#worlds",
  "handball-bundesliga": "/teams/handball/domestic#bundesliga",
  "olympic-mens-handball": "/teams/handball#olympics",
  "fivb-world-championship": "/teams/volleyball#worlds",
  "olympic-mens-volleyball": "/teams/volleyball#olympics",
  "summer-olympics-top-medalist": "/teams/olympics#all-time",
  "winter-olympics-top-medalist": "/teams/olympics#all-time",
  "wnba": "/teams/wnba#champions",
  "ncaa-w-champions": "/teams/cbb-w#champions",
  "fifa-womens-world-cup": "/teams/wnational#world-cup",
  "uefa-womens-championship": "/teams/wnational#euros",
  "uefa-womens-champions-league": "/teams/wfootball#club-tournaments",
  "wsl": "/teams/wfootball/leagues/england#champions",
  "nwsl": "/teams/wfootball/leagues/united-states#champions",
  "liga-f": "/teams/wfootball/leagues/spain#champions",
  "olympic-womens-football": "/teams/wnational#olympics",
};

// Dedicated hub path for a competition if one exists, else the honour roll.
export function competitionHref(compSlug: string): string {
  return COMP_TO_HUB[compSlug] ?? `/sports/champions/${compSlug}`;
}

// True when the competition has a dedicated hub (so no honour roll is built).
export function competitionHasHub(compSlug: string): boolean {
  return compSlug in COMP_TO_HUB;
}
