import "server-only";
import { readFileSync } from "fs";
import { join } from "path";

// Data is generated by scripts/build-f1-data.py from the "F1 Data" project
// (self-refreshing via the Jolpica-F1 API). Live current-season standings are
// pulled at request time in lib/f1Standings.ts (ESPN), with current_standings
// here as the fallback.

// ─── Types ─────────────────────────────────────────────────────────────────
export type F1Meta = {
  league: string; abbr: string; sport: string;
  first_season: number; latest_season: number;
  races_total: number; host_metros: number; circuits: number; generated: string;
};
export type F1Champion = {
  season: number;
  driver: string | null; driver_nat: string | null;
  driver_points: number | null; driver_wins: number | null;
  constructor: string | null; constructor_points: number | null; constructor_wins: number | null;
};
export type F1Title = { name: string; titles: number; years: number[]; nat?: string | null };
export type F1DriverWin = { driver: string; wins: number };
export type F1ConstructorWin = { constructor: string; wins: number };
export type F1Race = {
  season: number; round: number; race_name: string | null; date: string | null;
  circuit: string | null; circuit_id: string; city: string | null;
  metro: string; metro_slug: string; metro_resolved: boolean; country: string | null;
  winner: string | null; winner_constructor: string | null;
  pole: string | null; fastest_lap: string | null; laps: number | null;
  length: string | null; direction: string | null; ctype: string | null;
};
export type F1Circuit = {
  circuit_id: string; circuit_name: string | null; slug: string;
  metro: string | null; metro_slug: string; country: string | null;
  races: number; first_year: number; last_year: number;
  last_winner: string | null; last_winner_constructor: string | null;
  most_wins_driver: [string, number] | null;
  lat: number | null; lng: number | null; wikipedia: string | null;
};
export type F1HostMetro = {
  metro: string; metro_slug: string; metro_resolved: boolean; country: string | null;
  races: number; circuits: string[]; circuit_count: number;
  first_year: number; last_year: number;
  last_gp: { season: number; race_name: string | null; winner: string | null; constructor: string | null; circuit_id: string };
};
export type F1MetroRecent = {
  race_name: string | null; season: number; winner: string | null;
  constructor: string | null; circuit_id: string; races: number;
};
export type F1StandingRow = { pos: number | null; driver: string; nat: string | null; team: string | null; points: number | null; wins: number | null };
export type F1ConstructorRow = { pos: number | null; constructor: string; points: number | null; wins: number | null };
export type F1CurrentStandings = { season: number; round: number | null; drivers: F1StandingRow[]; constructors: F1ConstructorRow[] };

export type F1Data = {
  meta: F1Meta;
  champions: F1Champion[];
  driver_titles: F1Title[];
  constructor_titles: F1Title[];
  all_time_driver_wins: F1DriverWin[];
  all_time_constructor_wins: F1ConstructorWin[];
  circuits: F1Circuit[];
  circuit_detail: Record<string, F1Race[]>;
  host_metros: F1HostMetro[];
  metro_recent: Record<string, F1MetroRecent>;
  latest_season_races: F1Race[];
  current_standings: F1CurrentStandings;
};

// ─── Loader ────────────────────────────────────────────────────────────────
let _data: F1Data | null = null;
function loadData(): F1Data {
  if (_data === null) {
    _data = JSON.parse(
      readFileSync(join(process.cwd(), "public", "data", "f1", "data.json"), "utf-8")
    ) as F1Data;
  }
  return _data;
}

export function getF1Meta(): F1Meta { return loadData().meta; }
export function getF1Champions(): F1Champion[] { return loadData().champions; }
export function getF1DriverTitles(): F1Title[] { return loadData().driver_titles; }
export function getF1ConstructorTitles(): F1Title[] { return loadData().constructor_titles; }
export function getF1AllTimeDriverWins(): F1DriverWin[] { return loadData().all_time_driver_wins; }
export function getF1AllTimeConstructorWins(): F1ConstructorWin[] { return loadData().all_time_constructor_wins; }
export function getF1Circuits(): F1Circuit[] { return loadData().circuits; }
export function getF1HostMetros(): F1HostMetro[] { return loadData().host_metros; }
export function getF1LatestSeasonRaces(): F1Race[] { return loadData().latest_season_races; }
export function getF1CurrentStandingsFallback(): F1CurrentStandings { return loadData().current_standings; }

// Runtime ISR read of the live-season slice (race log + standings snapshot) from
// GitHub raw, so the f1-refresh Action's [vercel skip] data commits surface on the
// hub without a rebuild -- matching how the World Cup and leaders hubs stay fresh.
// Falls back to the build-time bundle on any failure.
const F1_DATA_RAW =
  "https://raw.githubusercontent.com/ashwin-desikan/metro-power-rankings/main/public/data/f1/data.json";
export async function fetchF1LiveSeason(): Promise<{ races: F1Race[]; standings: F1CurrentStandings }> {
  const fallback = () => ({ races: loadData().latest_season_races, standings: loadData().current_standings });
  try {
    const res = await fetch(F1_DATA_RAW, { next: { revalidate: 1800 } });
    if (!res.ok) return fallback();
    const d = (await res.json()) as F1Data;
    if (!d?.latest_season_races || !d?.current_standings) return fallback();
    return { races: d.latest_season_races, standings: d.current_standings };
  } catch {
    return fallback();
  }
}

export function getF1CircuitBySlug(slug: string): { circuit: F1Circuit; races: F1Race[] } | null {
  const d = loadData();
  const circuit = d.circuits.find((c) => c.slug === slug);
  if (!circuit) return null;
  return { circuit, races: d.circuit_detail[slug] ?? [] };
}
export function getAllF1CircuitSlugs(): string[] {
  return loadData().circuits.map((c) => c.slug);
}

// Most recent Grand Prix held in a metro (by site metro slug), for the metro page card.
export function getF1RecentWinnerForMetro(metroSlug: string): F1MetroRecent | null {
  return loadData().metro_recent[metroSlug] ?? null;
}

// Look up a single Grand Prix result by its event name + year (e.g. "Monaco
// Grand Prix", 2024). Used to enrich the "F1 Races" cards in the Major Sporting
// Events section on metro pages with the winner and a link to the circuit page.
let _raceIndex: Record<string, { circuit_id: string; winner: string | null; constructor: string | null }> | null = null;
export function getF1RaceResultByName(
  raceName: string, year: number | string
): { circuit_id: string; winner: string | null; constructor: string | null } | null {
  if (_raceIndex === null) {
    _raceIndex = {};
    const d = loadData();
    for (const cid of Object.keys(d.circuit_detail)) {
      for (const r of d.circuit_detail[cid]) {
        if (r.race_name) {
          _raceIndex[`${r.race_name}|${r.season}`] = {
            circuit_id: r.circuit_id, winner: r.winner, constructor: r.winner_constructor,
          };
        }
      }
    }
  }
  return _raceIndex[`${raceName}|${year}`] ?? null;
}
