// lib/flags.ts
// Slug -> flag code (ISO 3166-1 alpha-2, or flagcdn subdivision code for the
// UK home nations). Flag IMAGES are used, not emoji: Windows browsers render
// flag emoji as bare letter pairs, so we serve pngs from flagcdn.com.
// Generated from public/data/countries.json names (pycountry) + manual overrides
// for territories and constituents. A handful of de-facto states
// (Transnistria, Abkhazia, Northern Cyprus, South Ossetia) have no code and
// intentionally render no flag.

export const FLAG_CODE: Record<string, string> = {
  "EU": "eu",
  "UN": "un",
  "afghanistan": "af",
  "albania": "al",
  "algeria": "dz",
  "american-samoa": "as",
  "andorra": "ad",
  "angola": "ao",
  "anguilla": "ai",
  "antigua-barbuda": "ag",
  "argentina": "ar",
  "armenia": "am",
  "aruba": "aw",
  "australia": "au",
  "austria": "at",
  "azerbaijan": "az",
  "bahamas": "bs",
  "bahrain": "bh",
  "bangladesh": "bd",
  "barbados": "bb",
  "belarus": "by",
  "belgium": "be",
  "belize": "bz",
  "benin": "bj",
  "bermuda": "bm",
  "bhutan": "bt",
  "bolivia": "bo",
  "bonaire": "bq",
  "bosnia-herzegovina": "ba",
  "botswana": "bw",
  "brazil": "br",
  "british-virgin-islands": "vg",
  "brunei": "bn",
  "bulgaria": "bg",
  "burkina-faso": "bf",
  "burundi": "bi",
  "cambodia": "kh",
  "cameroon": "cm",
  "canada": "ca",
  "cape-verde": "cv",
  "cayman-islands": "ky",
  "central-african-republic": "cf",
  "chad": "td",
  "chile": "cl",
  "china": "cn",
  "colombia": "co",
  "comoros": "km",
  "congo": "cg",
  "congo-dr": "cd",
  "cook-islands": "ck",
  "costa-rica": "cr",
  "cote-divoire": "ci",
  "croatia": "hr",
  "cuba": "cu",
  "curacao": "cw",
  "cyprus": "cy",
  "czech-republic": "cz",
  "denmark": "dk",
  "djibouti": "dj",
  "dominica": "dm",
  "dominican-republic": "do",
  "east-timor": "tl",
  "ecuador": "ec",
  "egypt": "eg",
  "el-salvador": "sv",
  "england": "gb-eng",
  "equatorial-guinea": "gq",
  "eritrea": "er",
  "estonia": "ee",
  "eswatini": "sz",
  "ethiopia": "et",
  "falkland-islands": "fk",
  "faroe-islands": "fo",
  "federated-states-of-micronesia": "fm",
  "fiji": "fj",
  "finland": "fi",
  "france": "fr",
  "french-guiana": "gf",
  "gabon": "ga",
  "gambia": "gm",
  "georgia": "ge",
  "germany": "de",
  "ghana": "gh",
  "gibraltar": "gi",
  "greece": "gr",
  "greenland": "gl",
  "grenada": "gd",
  "guadeloupe": "gp",
  "guam": "gu",
  "guatemala": "gt",
  "guernsey": "gg",
  "guinea": "gn",
  "guinea-bissau": "gw",
  "guyana": "gy",
  "haiti": "ht",
  "honduras": "hn",
  "hong-kong": "hk",
  "hungary": "hu",
  "iceland": "is",
  "india": "in",
  "indonesia": "id",
  "iran": "ir",
  "iraq": "iq",
  "ireland": "ie",
  "isle-of-man": "im",
  "israel": "il",
  "italy": "it",
  "jamaica": "jm",
  "japan": "jp",
  "jersey": "je",
  "jordan": "jo",
  "kazakhstan": "kz",
  "kenya": "ke",
  "kiribati": "ki",
  "kosovo": "xk",
  "kuwait": "kw",
  "kyrgyzstan": "kg",
  "laos": "la",
  "latvia": "lv",
  "lebanon": "lb",
  "lesotho": "ls",
  "liberia": "lr",
  "libya": "ly",
  "liechtenstein": "li",
  "lithuania": "lt",
  "luxembourg": "lu",
  "macau": "mo",
  "madagascar": "mg",
  "malawi": "mw",
  "malaysia": "my",
  "maldives": "mv",
  "mali": "ml",
  "malta": "mt",
  "marshall-islands": "mh",
  "martinique": "mq",
  "mauritania": "mr",
  "mauritius": "mu",
  "mayotte": "yt",
  "mexico": "mx",
  "moldova": "md",
  "monaco": "mc",
  "mongolia": "mn",
  "montenegro": "me",
  "montserrat": "ms",
  "morocco": "ma",
  "mozambique": "mz",
  "myanmar": "mm",
  "namibia": "na",
  "nauru": "nr",
  "nepal": "np",
  "netherlands": "nl",
  "new-caledonia": "nc",
  "new-zealand": "nz",
  "nicaragua": "ni",
  "niger": "ne",
  "nigeria": "ng",
  "niue": "nu",
  "north-korea": "kp",
  "north-macedonia": "mk",
  "northern-ireland": "gb-nir",
  "northern-mariana-islands": "mp",
  "norway": "no",
  "oman": "om",
  "pakistan": "pk",
  "palau": "pw",
  "palestine": "ps",
  "panama": "pa",
  "papua-new-guinea": "pg",
  "paraguay": "py",
  "peru": "pe",
  "philippines": "ph",
  "poland": "pl",
  "portugal": "pt",
  "puerto-rico": "pr",
  "qatar": "qa",
  "reunion": "re",
  "romania": "ro",
  "russia": "ru",
  "rwanda": "rw",
  "saba": "bq",
  "saint-barthelemy": "bl",
  "saint-helena-ascension-and-tristan-da-cunha": "sh",
  "saint-lucia": "lc",
  "saint-martin": "mf",
  "saint-pierre-and-miquelon": "pm",
  "samoa": "ws",
  "san-marino": "sm",
  "sao-tome-and-principe": "st",
  "saudi-arabia": "sa",
  "scotland": "gb-sct",
  "senegal": "sn",
  "serbia": "rs",
  "seychelles": "sc",
  "sierra-leone": "sl",
  "singapore": "sg",
  "sint-eustatius": "bq",
  "sint-maarten": "sx",
  "slovakia": "sk",
  "slovenia": "si",
  "solomon-islands": "sb",
  "somalia": "so",
  "south-africa": "za",
  "south-korea": "kr",
  "south-sudan": "ss",
  "spain": "es",
  "sri-lanka": "lk",
  "st-kitts-nevis": "kn",
  "st-vincent-the-grenadines": "vc",
  "sudan": "sd",
  "suriname": "sr",
  "sweden": "se",
  "switzerland": "ch",
  "syria": "sy",
  "tahiti": "pf",
  "taiwan": "tw",
  "tajikistan": "tj",
  "tanzania": "tz",
  "thailand": "th",
  "togo": "tg",
  "tokelau": "tk",
  "tonga": "to",
  "trinidad-tobago": "tt",
  "tunisia": "tn",
  "turkey": "tr",
  "turkmenistan": "tm",
  "turks-caicos-islands": "tc",
  "tuvalu": "tv",
  "uganda": "ug",
  "ukraine": "ua",
  "united-arab-emirates": "ae",
  "united-kingdom": "gb",
  "united-states": "us",
  "uruguay": "uy",
  "us-virgin-islands": "vi",
  "uzbekistan": "uz",
  "vanuatu": "vu",
  "vatican-city": "va",
  "venezuela": "ve",
  "vietnam": "vn",
  "wales": "gb-wls",
  "wallis-and-futuna": "wf",
  "western-sahara": "eh",
  "yemen": "ye",
  "zambia": "zm",
  "zimbabwe": "zw",
};

// flagcdn supports fixed sizes like 20x15 and 40x30 (4:3). Returns null when
// we have no code for the slug so callers can render nothing gracefully.
export function flagUrl(slug: string): string | null {
  const code = FLAG_CODE[slug];
  return code ? `https://flagcdn.com/20x15/${code}.png` : null;
}

export function flagSrcSet(slug: string): string | null {
  const code = FLAG_CODE[slug];
  return code ? `https://flagcdn.com/40x30/${code}.png 2x` : null;
}

// Build a flagcdn URL from a raw code (used for historical eras whose flag
// equals a current country's, e.g. West Germany → "de", Czechoslovakia → "cz").
export function flagUrlByCode(code: string): string {
  return `https://flagcdn.com/20x15/${code}.png`;
}
export function flagSrcSetByCode(code: string): string {
  return `https://flagcdn.com/40x30/${code}.png 2x`;
}
