// Gold Standard = the apex top-flight competition in each sport. Shared
// between the /sports filter explorer (chip badges, preset gate) and the
// metro page TeamCards (badge next to each team in the metro's roster).
//
// Renamed from 'Crown Jewels' on 2026-05-16. The 👑 crown emoji is
// reserved elsewhere for the Top Team designation per metro; 🥇 marks
// Gold Standard, 🥈 marks non-Gold Major League.
//
// Refactored 2026-05-17 to be workbook-driven via scripts/extract.py.
// The Team List sheet now carries a 'Gold Standard' column (col L); the
// ETL aggregates flagged rows into public/data/gold-standard-leagues.json
// keyed by sport. lib/goldStandard.ts statically imports that JSON and
// layers a curated FOOTBALL_BIG_FIVE override on top because the workbook
// intentionally leaves men's Football Gold blank (the user's editorial
// position is that England / Spain / Italy / France / Germany top flights
// remain Gold regardless of workbook state).

import goldData from "@/public/data/gold-standard-leagues.json";

// Workbook-driven gold leagues, keyed by sport (e.g. "Baseball" -> ["MLB"]).
// The JSON file is generated by scripts/extract_gold_standard_leagues in
// scripts/extract.py; do not edit by hand.
const WORKBOOK_GOLD: Record<string, readonly string[]> =
  (goldData as { sports: Record<string, string[]> }).sports;

// Curated override: men's Football Big 5 stays Gold even though the
// workbook leaves these rows blank. This is an editorial decision, not a
// workbook gap. The user's position is that England / Spain / Italy /
// France / Germany top flights remain Gold regardless of workbook state.
const FOOTBALL_BIG_FIVE = new Set(["England", "Spain", "Italy", "France", "Germany"]);

export const GOLD_STANDARD_LEAGUES_BY_SPORT: Record<string, ReadonlySet<string>> = {
  ...Object.fromEntries(
    Object.entries(WORKBOOK_GOLD).map(([sport, leagues]) => [sport, new Set(leagues)])
  ),
  // Layer Football men's Big 5 over (or alongside) anything the workbook may
  // add to "Football" in the future. Spread-then-merge so a future workbook
  // entry under "Football" augments rather than replaces the Big 5.
  Football: new Set([
    ...(WORKBOOK_GOLD["Football"] ?? []),
    ...FOOTBALL_BIG_FIVE,
  ]),
};

export function isGoldStandardLeague(sport: string, league: string): boolean {
  // The workbook stores football as 'Football' in Team List but as 'Soccer'
  // when the FootballClub_Data sheet is merged in scripts/extract.py for
  // metro detail pages. Normalize both to the Football set.
  const s = sport === "Soccer" ? "Football" : sport;
  return GOLD_STANDARD_LEAGUES_BY_SPORT[s]?.has(league) ?? false;
}
