import "server-only";
import { readFileSync } from "fs";
import { join } from "path";
import { getStatesDirectory } from "./statesDirectory";
import { getAllStates } from "./states";

// Civic-facts enrichment layer for /states pages. Two sources, merged at read
// time and cached:
//   - public/data/states-facts.json      Wikidata civic pack, PIPELINE-OWNED
//     (regenerated by scripts/states/build-state-facts.py --enrich --fresh).
//   - public/data/state-representation.json  CURATED political representation,
//     kept SEPARATE so a pipeline regen never clobbers it.
// The workbook (states.json) stays the ground truth for the core; this only
// adds the "At a glance" fields the pages lacked.

export type StateRepresentation = {
  electoralVotes?: number;
  lowerSeats?: number;   // US House, India Lok Sabha, ...
  lowerHouse?: string;   // display label for lowerSeats
  upperSeats?: number;   // US Senators, German Bundesrat votes, ...
  upperHouse?: string;   // display label for upperSeats
};

export type StateFacts = {
  iso?: string | null;
  name?: string;
  country?: string;
  flag?: string;
  emblem?: string;
  areaKm2?: number;
  founded?: number;
  demonym?: string;
  nickname?: string;
  endonym?: string;
  legislature?: string;
  hdi?: number;
  hdiYear?: string | number;
  gdpUsd?: number;
  gdpPerCapitaUsd?: number;
  gdpYear?: number;
  highestPoint?: string;
  highestPointM?: number;
  representation?: StateRepresentation;
};

// Read via a thunk so the readFileSync path stays a LITERAL at the call site.
// A dynamic filename arg makes Turbopack bundle the whole public/data tree.
function readData<T>(read: () => string, fallback: T): T {
  try {
    return JSON.parse(read()) as T;
  } catch {
    return fallback;
  }
}

let _merged: Record<string, StateFacts> | null = null;

function allFacts(): Record<string, StateFacts> {
  if (_merged) return _merged;
  const base = readData<Record<string, StateFacts>>(
    () =>
      readFileSync(
        join(process.cwd(), "public", "data", "states-facts.json"),
        "utf-8",
      ),
    {},
  );
  const rep = readData<Record<string, StateRepresentation>>(
    () =>
      readFileSync(
        join(process.cwd(), "public", "data", "state-representation.json"),
        "utf-8",
      ),
    {},
  );
  // Wikidata returns Commons image URLs as http://; upgrade to https:// so they
  // don't get blocked as mixed content on the https site.
  for (const k of Object.keys(base)) {
    const f = base[k];
    if (f.flag && f.flag.startsWith("http://")) f.flag = "https://" + f.flag.slice(7);
    if (f.emblem && f.emblem.startsWith("http://")) f.emblem = "https://" + f.emblem.slice(7);
  }
  for (const [slug, r] of Object.entries(rep)) {
    if (!base[slug]) base[slug] = {};
    base[slug].representation = r;
  }
  const hdi = readData<Record<string, { hdi?: number; hdiYear?: number }>>(
    () =>
      readFileSync(
        join(process.cwd(), "public", "data", "state-hdi.json"),
        "utf-8",
      ),
    {},
  );
  for (const [slug, h] of Object.entries(hdi)) {
    if (!base[slug]) base[slug] = {};
    if (h.hdi != null) base[slug].hdi = h.hdi;
    if (h.hdiYear != null) base[slug].hdiYear = h.hdiYear;
  }
  // Hand-curated overlay (wins) for divisions Wikidata models poorly, e.g.
  // Portugal's traditional districts and Chandigarh.
  const curated = readData<Record<string, Partial<StateFacts>>>(
    () =>
      readFileSync(
        join(process.cwd(), "public", "data", "state-curated.json"),
        "utf-8",
      ),
    {},
  );
  for (const [slug, c] of Object.entries(curated)) {
    if (!base[slug]) base[slug] = {};
    Object.assign(base[slug], c);
  }
  _merged = base;
  return _merged;
}

export function getStateFacts(slug: string): StateFacts | null {
  return allFacts()[slug] ?? null;
}

// Rank of a division among all first-level divisions of the SAME sovereign, by
// the states-directory composite score. Returns null if the slug isn't in the
// directory or its country has only one entry.
let _rankCache: Map<string, { rank: number; total: number }> | null = null;

export function getInCountryRank(
  slug: string,
): { rank: number; total: number } | null {
  if (!_rankCache) {
    _rankCache = new Map();
    // Rank only among TRUE first-level divisions of the sovereign: a division
    // whose immediate parent (states.json `country`) is its sovereign
    // (`mainCountry`). Drops territory sub-units (e.g. Guam municipalities) that
    // otherwise inflate the United States group from 51 to 83. Ranks by the
    // states-directory weighted score, matching the /states directory itself.
    const sovereignOf = new Map<string, string>();
    for (const st of getAllStates()) {
      if (st.country === st.mainCountry) sovereignOf.set(st.slug, st.mainCountry);
    }
    const byCountry = new Map<string, { slug: string; score: number }[]>();
    for (const r of getStatesDirectory()) {
      const sov = sovereignOf.get(r.slug);
      if (!sov) continue;
      if (!byCountry.has(sov)) byCountry.set(sov, []);
      byCountry.get(sov)!.push({ slug: r.slug, score: r.score });
    }
    for (const rows of byCountry.values()) {
      const sorted = [...rows].sort((a, b) => b.score - a.score);
      sorted.forEach((r, i) =>
        _rankCache!.set(r.slug, { rank: i + 1, total: sorted.length }),
      );
    }
  }
  const hit = _rankCache.get(slug);
  return hit && hit.total > 1 ? hit : null;
}

// Rank of a division by area among the first-level divisions of the same
// sovereign that have an area on record.
let _areaCache: Map<string, { rank: number; total: number }> | null = null;

export function getAreaRank(
  slug: string,
): { rank: number; total: number } | null {
  if (!_areaCache) {
    _areaCache = new Map();
    const facts = allFacts();
    const byCountry = new Map<string, { slug: string; area: number }[]>();
    for (const st of getAllStates()) {
      if (st.country !== st.mainCountry) continue;
      const a = facts[st.slug]?.areaKm2;
      if (a == null) continue;
      if (!byCountry.has(st.mainCountry)) byCountry.set(st.mainCountry, []);
      byCountry.get(st.mainCountry)!.push({ slug: st.slug, area: a });
    }
    for (const rows of byCountry.values()) {
      const sorted = [...rows].sort((a, b) => b.area - a.area);
      sorted.forEach((r, i) =>
        _areaCache!.set(r.slug, { rank: i + 1, total: sorted.length }),
      );
    }
  }
  const hit = _areaCache.get(slug);
  return hit && hit.total > 1 ? hit : null;
}
