// Top Sports Teams reference data. Source of truth for /top-teams.
// Generated from the "Top Sports Teams" sheet in MetroAreas.xlsx by
// scripts/_emit_topteams_ts.py. Hand-edits to this file will be
// overwritten on next regeneration. Edit the xlsx instead and rerun.
//
// Rank refers to the parent metro's rank in the Global Metro Power
// Rankings composite. Sport is the dataset label (Football, American
// Football, Baseball, Basketball, Hockey, T20 Cricket, etc.). Team is
// the single franchise the metro is identified with; "/" separates
// genuinely co-equal picks (Arsenal / Chelsea, Inter / AC Milan).

export interface TopTeamPick {
  rank: number;
  metro: string;
  sport: string;
  team: string;
  rationale: string;
}

export const TOP_TEAMS: TopTeamPick[] = [
  {
    rank: 1,
    metro: "New York",
    sport: "Baseball",
    team: "New York Yankees",
    rationale: "27 World Series titles — the most in any North American pro sport. Arguably the most valuable and globally recognized franchise in American sports; Yankee Stadium and the pinstripes are global icons. Runners-up: Knicks, Giants, Rangers, Mets.",
  },
  {
    rank: 2,
    metro: "London",
    sport: "Football",
    team: "Arsenal / Chelsea",
    rationale: "Arsenal: 13 English league titles (3rd-most in English football), 14 FA Cups (most ever), the 2003-04 Invincibles (only modern unbeaten Premier League season), and the longest unbroken run in the English top flight. Chelsea: 6 English league titles (5 in the Abramovich era), 2 UEFA Champions League titles (2012, 2021), 2 UEFA Europa League titles (2013, 2019), and 2025 FIFA Club World Cup champions — more European silverware than any London club. Genuinely co-equal — Arsenal on domestic history and global fanbase, Chelsea on European pedigree and recent trophy density. Tottenham (2 league titles, last in 1961) trails both.",
  },
  {
    rank: 3,
    metro: "Paris",
    sport: "Football",
    team: "Paris Saint-Germain",
    rationale: "French football's dominant force since 2011 — 13 Ligue 1 titles, 2025 UEFA Champions League winners, home of the Mbappé/Neymar/Messi era. No other Paris club competes on the global stage.",
  },
  {
    rank: 4,
    metro: "Tokyo",
    sport: "Baseball",
    team: "Yomiuri Giants",
    rationale: "Japan's most historic and decorated baseball franchise — 22 Japan Series titles, often called the 'Yankees of Japan.' National following far beyond Tokyo. FC Tokyo and Tokyo Verdy exist in J-League but have far less cultural weight.",
  },
  {
    rank: 5,
    metro: "San Francisco-San Jose",
    sport: "American Football",
    team: "San Francisco 49ers",
    rationale: "5 Super Bowl titles, the Montana/Rice dynasty, and currently an NFL powerhouse. Globally more recognized than the Giants or Warriors, though the Warriors (4 titles 2015-22) have a near-equal claim for the modern era.",
  },
  {
    rank: 6,
    metro: "Beijing",
    sport: "Football",
    team: "Beijing Guoan",
    rationale: "Flagship club of the Chinese capital since 1992, 2009 CSL champions, massive Workers' Stadium fanbase. CBA's Beijing Ducks (3 titles) are a credible alternative in basketball.",
  },
  {
    rank: 7,
    metro: "Seoul",
    sport: "Football",
    team: "FC Seoul",
    rationale: "6 K League titles, largest average attendance in Korean football, plays at Seoul World Cup Stadium. LG Twins (KBO, 2023 Korean Series champions) are a strong co-choice given baseball's popularity in Korea.",
  },
  {
    rank: 8,
    metro: "Los Angeles",
    sport: "Basketball",
    team: "Los Angeles Lakers",
    rationale: "17 NBA titles (tied-most), Magic/Kareem/Shaq/Kobe/LeBron dynasties, global brand rivaling any sports franchise. Dodgers (8 WS, 2024 & 2025 champs) have an equal claim — either is defensible.",
  },
  {
    rank: 9,
    metro: "Shanghai",
    sport: "Football",
    team: "Shanghai Port",
    rationale: "2018 and 2023 CSL champions, city's flagship football side backed by SIPG. Shanghai Sharks (CBA, Yao Ming's former club) are a historic alternative.",
  },
  {
    rank: 10,
    metro: "Guangzhou",
    sport: "Football",
    team: "Guangzhou FC",
    rationale: "Historically China's most successful club — 8 CSL titles (2011-19), 2 AFC Champions League titles (2013, 2015), the Chinese football era-definer before its financial collapse.",
  },
  {
    rank: 11,
    metro: "Washington-Baltimore",
    sport: "American Football",
    team: "Baltimore Ravens / Washington Commanders",
    rationale: "Ravens: 2 Super Bowl titles (2001, 2013), consistent contender, Lamar Jackson era. Commanders: 3 Super Bowl titles (1982, 1987, 1991) in Gibbs era and one of the NFL's most historic franchises — currently rebuilt into a contender with Jayden Daniels. Two separate NFL markets in a shared metro, each dominant in its own city. Capitals (2018 Cup) and Orioles follow.",
  },
  {
    rank: 12,
    metro: "Chicago",
    sport: "American Football",
    team: "Chicago Bears",
    rationale: "9 NFL championships (tied-most in NFL history alongside Packers), Super Bowl XX champions (1985) — one of the most iconic teams in NFL history with the Monsters of the Midway legacy, '85 Bears defense, and Ditka/Payton/Butkus/Singletary cultural icons. Chicago's oldest and most historic franchise (founded 1920, NFL charter member). Bulls' 90s dynasty had a bigger global moment, but the Bears are Chicago's soul. Cubs (2016 WS) and Blackhawks (3 Cups 2010s) follow.",
  },
  {
    rank: 13,
    metro: "Boston",
    sport: "Baseball",
    team: "Boston Red Sox",
    rationale: "9 World Series titles (most recently 2004, 2007, 2013, 2018) — the 2004 curse-breaker is one of the defining moments in American sports history. Fenway Park (1912) is baseball's oldest ballpark and a national landmark. Celtics (18 NBA titles) and Patriots (6 Super Bowls, Brady era) both have equal claims — all three defensible.",
  },
  {
    rank: 14,
    metro: "Osaka-Kyoto-Kobe",
    sport: "Baseball",
    team: "Hanshin Tigers",
    rationale: "Japan's most fanatical fanbase (Koshien Stadium), 2023 Japan Series champions breaking a 38-year drought. Cultural institution in Kansai rivaling any sports team anywhere.",
  },
  {
    rank: 15,
    metro: "Sydney",
    sport: "Rugby League",
    team: "Penrith Panthers",
    rationale: "4 consecutive NRL premierships (2021, 2022, 2023, 2024) — first team to four-peat in the NRL era and one of the most dominant runs in Australian sports history, led by Nathan Cleary and Ivan Cleary. 5 total premierships. Sydney Roosters (15 premierships, joint-most in rugby league history) are the historic choice; Sydney Swans (AFL, 5 premierships incl. 2022 GF) and South Sydney Rabbitohs (21 titles across eras) round out a deep Sydney market.",
  },
  {
    rank: 16,
    metro: "Toronto",
    sport: "Hockey",
    team: "Toronto Maple Leafs",
    rationale: "13 Stanley Cups (3rd most in NHL), Canada's most valuable and culturally central franchise despite long title drought. Raptors (2019 NBA champs) and Blue Jays (2 WS) have cases.",
  },
  {
    rank: 17,
    metro: "Moscow",
    sport: "Basketball",
    team: "PBC CSKA Moscow",
    rationale: "8-time Euroleague champion (tied with Real Madrid for most in European history), Russia's most dominant sports club across eras. FC Spartak Moscow (10 Soviet + 10 Russian football titles) is an equally defensible pick.",
  },
  {
    rank: 18,
    metro: "Hong Kong",
    sport: "Football",
    team: "Kitchee SC",
    rationale: "Most successful Hong Kong football club of the modern era — 9 league titles, only HK club to reach AFC Champions League group stage. Hong Kong's sports scene is thin globally.",
  },
  {
    rank: 19,
    metro: "Milan",
    sport: "Football",
    team: "Internazionale / AC Milan",
    rationale: "Internazionale: 20 Serie A titles (tied-most with Juventus), 3 UEFA Champions League titles (1964, 1965, 2010), 2010 continental treble under Mourinho, and 2024 Serie A champions — currently the dominant Milan club. AC Milan: 19 Serie A titles, 7 European Cups/UCLs (2nd-most in Europe behind Real Madrid), 2022 Serie A champions. Genuinely co-equal — Inter edges on Serie A trophies (20 vs 19) and the 2010 treble, AC Milan on European Cup pedigree (7 vs 3). San Siro is shared. One of world football's great two-horse metros.",
  },
  {
    rank: 20,
    metro: "Madrid",
    sport: "Football",
    team: "Real Madrid",
    rationale: "Undisputed most decorated football club in history — 36 La Liga titles, 15 UEFA Champions League titles (most ever). FIFA Club of the 20th Century. No serious competition globally.",
  },
  {
    rank: 21,
    metro: "Istanbul",
    sport: "Football",
    team: "Galatasaray SK / Fenerbahçe SK",
    rationale: "Galatasaray: 25 Süper Lig titles (most ever in Turkish football), 2000 UEFA Cup and 2000 UEFA Super Cup — the only Turkish club to win a major European trophy. Fenerbahçe: 19 Süper Lig titles, Turkey's oldest club (founded 1907), consistent European participant and currently challenging Gala for the national title. Genuinely co-equal — Galatasaray edges on trophies (25 vs 19) and the lone European trophy, Fenerbahçe on history and fanbase scale. The Kıtalar Arası Derbi (Intercontinental Derby) is one of world football's fiercest rivalries. Beşiktaş JK (16 titles) is the historic third side.",
  },
  {
    rank: 22,
    metro: "Rhine-Ruhr",
    sport: "Football",
    team: "Borussia Dortmund",
    rationale: "8 Bundesliga titles, 1997 UCL champions, cult Yellow Wall at Westfalenstadion — one of Europe's most atmospheric clubs. Schalke 04 is the historic rival.",
  },
  {
    rank: 23,
    metro: "Houston",
    sport: "Baseball",
    team: "Houston Astros",
    rationale: "2 World Series (2017, 2022) and 7 consecutive ALCS appearances. Rockets (2 NBA titles, 1994-95 Olajuwon era) have an equal claim. Texans remain NFL title-less.",
  },
  {
    rank: 24,
    metro: "Sao Paulo",
    sport: "Football",
    team: "São Paulo",
    rationale: "6 Brasileirão titles, 3 Copa Libertadores, 3 FIFA Club World Cups (including the 1992/1993 back-to-back Intercontinental Cups) — Brazil's most internationally decorated club. Corinthians (7 titles, 2012 CWC) and Palmeiras (12 titles, 3 Libertadores) all have claims.",
  },
  {
    rank: 25,
    metro: "Singapore",
    sport: "Football",
    team: "Lion City Sailors",
    rationale: "2021 and 2024 Singapore Premier League champions, Singapore's most ambitious modern club. Albirex Niigata Singapore historically dominant. Singapore's club scene is thin globally.",
  },
  {
    rank: 26,
    metro: "Melbourne",
    sport: "Aussie Rules",
    team: "Collingwood Magpies",
    rationale: "16 VFL/AFL premierships (tied for most ever with Essendon and Carlton), 2023 AFL premiers. The most supported club in Australian sports — Collingwood membership and fan base dwarfs every other AFL team, and the Magpies are the defining cultural institution of Melbourne sport. Essendon (16 flags) and Carlton (16 flags) are historic equals on trophies but trail in modern fanbase. Melbourne Storm (NRL, 4 premierships) are the cross-code alternative.",
  },
  {
    rank: 27,
    metro: "Miami",
    sport: "American Football",
    team: "Miami Dolphins",
    rationale: "2 Super Bowl titles (1972, 1973) and the only **Perfect Season** in NFL history (1972, 17-0) — one of the most legendary achievements in American sports. Shula/Marino era cemented the Dolphins as Miami's defining franchise. Heat (3 NBA titles, LeBron/Wade era) have the modern trophy count; Inter Miami (Messi era) owns the global spotlight but is title-thin; Marlins (2 WS).",
  },
  {
    rank: 28,
    metro: "Mexico City",
    sport: "Football",
    team: "CF América",
    rationale: "Most titled club in Mexican football — 16 Liga MX titles (most ever), 7 CONCACAF Champions Leagues (tied-most), and Mexico's most popular and most hated club. Estadio Azteca home. Cruz Azul and Pumas UNAM are cross-town rivals.",
  },
  {
    rank: 29,
    metro: "Philadelphia",
    sport: "American Football",
    team: "Philadelphia Eagles",
    rationale: "2 Super Bowl titles (2017, 2024), currently the NFL's premier franchise. 76ers (3 titles, 1983 last), Phillies (2 WS), Flyers (2 Cups) all historic. Eagles are the city's soul.",
  },
  {
    rank: 30,
    metro: "Seattle",
    sport: "American Football",
    team: "Seattle Seahawks",
    rationale: "Super Bowl XLVIII champions (2013), NFL's loudest stadium. Seattle Sounders FC (2 MLS Cups, 2022 CONCACAF CL winners) and Storm (4 WNBA titles) are credible alternatives — Seattle is multi-sport strong.",
  },
  {
    rank: 31,
    metro: "Berlin",
    sport: "Basketball",
    team: "Alba Berlin",
    rationale: "11 Basketball Bundesliga titles — actually the metro's most decorated pro franchise. In football: Hertha BSC Berlin (2 German titles, 1930-31) is the historic club; 1. FC Union Berlin the modern cult success.",
  },
  {
    rank: 32,
    metro: "Barcelona",
    sport: "Football",
    team: "FC Barcelona",
    rationale: "28 La Liga titles, 5 UEFA Champions League titles, the Messi/Xavi/Iniesta tiki-taka era. One of the two or three most recognized sports brands on the planet. 'Més que un club.'",
  },
  {
    rank: 33,
    metro: "Dallas",
    sport: "American Football",
    team: "Dallas Cowboys",
    rationale: "5 Super Bowl titles and 'America's Team' — the most valuable sports franchise in the world by Forbes valuation (~$11B+). Cultural icon status in the NFL. Mavericks (2011 title) and Stars (1999 Cup) follow.",
  },
  {
    rank: 34,
    metro: "Atlanta",
    sport: "Baseball",
    team: "Atlanta Braves",
    rationale: "4 World Series titles (1957, 1995, 2021), 14 consecutive division titles 1991-2005 — one of MLB's historic franchises. Hawks and Falcons (no titles) trail significantly.",
  },
  {
    rank: 35,
    metro: "Dubai-Sharjah",
    sport: "Football",
    team: "Shabab Al Ahli Dubai",
    rationale: "9 UAE Pro League titles, Dubai's most decorated football club. Al-Wasl is the historic cross-town rival. Dubai also a major cricket neutral venue but no dominant cricket club.",
  },
  {
    rank: 36,
    metro: "Mumbai",
    sport: "T20 Cricket",
    team: "Mumbai Indians",
    rationale: "5 Indian Premier League titles (tied-most with CSK), led by Rohit Sharma and the Ambani family. Most valuable IPL franchise and one of India's most decorated T20 clubs. Mumbai City FC (2022-23 ISL champions) leads in football.",
  },
  {
    rank: 37,
    metro: "Bangkok",
    sport: "Football",
    team: "BG Pathum United",
    rationale: "2020-21 Thai League 1 champions, currently Bangkok-metro's flagship top-flight side. Bangkok United and Port FC are co-rivals. Nationally Buriram United dominates.",
  },
  {
    rank: 38,
    metro: "Kuala Lumpur",
    sport: "Football",
    team: "Selangor FC",
    rationale: "33-time Malaysia Cup winners (most ever), historically the dominant KL-area football club. Kuala Lumpur City FC also competes.",
  },
  {
    rank: 39,
    metro: "Amsterdam",
    sport: "Football",
    team: "AFC Ajax",
    rationale: "36 Eredivisie titles (most ever), 4 UEFA Champions League / European Cup titles including the 1971-73 three-peat, and 1995 Champions League — one of football's most storied academies and clubs globally.",
  },
  {
    rank: 40,
    metro: "Buenos Aires",
    sport: "Football",
    team: "Boca Juniors",
    rationale: "35 Argentine Primera titles, 6 Copa Libertadores (tied-most), home of Maradona's myth at La Bombonera. River Plate (38 titles, 4 Libertadores) is an equally valid choice — two of the biggest clubs on earth share this metro.",
  },
  {
    rank: 41,
    metro: "Munich",
    sport: "Football",
    team: "Bayern Munich",
    rationale: "34 Bundesliga titles (most ever, including 11 consecutive 2013-2023), 6 UEFA Champions League titles, 2013 and 2020 continental trebles. Germany's dominant sports franchise by any measure.",
  },
  {
    rank: 42,
    metro: "Brussels",
    sport: "Football",
    team: "RSC Anderlecht",
    rationale: "34 Belgian league titles (most ever), 2 UEFA Cup Winners' Cups, 1 UEFA Cup. Historically Belgium's flagship club; Club Brugge has recently overtaken nationally but Anderlecht remains Brussels' icon.",
  },
  {
    rank: 43,
    metro: "Manila",
    sport: "Basketball",
    team: "Barangay Ginebra San Miguel",
    rationale: "15 PBA championships, the most popular basketball franchise in the Philippines — basketball is the Philippines' true national sport. 'Never Say Die' fanbase unmatched in Asia.",
  },
  {
    rank: 44,
    metro: "Nanjing",
    sport: "Basketball",
    team: "Jiangsu Dragons",
    rationale: "2 CBA Finals appearances, metro's current flagship pro franchise. Jiangsu FC won 2020 CSL then folded in 2021 — metro lacks a sustained top-tier football club.",
  },
  {
    rank: 45,
    metro: "Frankfurt",
    sport: "Football",
    team: "Eintracht Frankfurt",
    rationale: "1 Bundesliga title (1959), 2022 UEFA Europa League champions, 2023 DFB-Pokal. Frankfurt's defining sports club with a famously raucous fanbase.",
  },
  {
    rank: 46,
    metro: "Vienna",
    sport: "Football",
    team: "SK Rapid Wien",
    rationale: "32 Austrian Bundesliga titles (most ever). FK Austria Wien (24 titles) is the cross-town rival — Rapid edges on historical dominance.",
  },
  {
    rank: 47,
    metro: "Jakarta",
    sport: "Football",
    team: "Persija Jakarta",
    rationale: "11 Indonesian top-flight titles (most ever), huge Jakmania fanbase, plays at Gelora Bung Karno. Most historic Indonesian football club.",
  },
  {
    rank: 48,
    metro: "Chengdu",
    sport: "Football",
    team: "Chengdu Rongcheng",
    rationale: "Metro's current CSL side, no titles. City's most globally known sports identity is the Chengdu Pandas and event hosting rather than any team.",
  },
  {
    rank: 49,
    metro: "Rome",
    sport: "Football",
    team: "AS Roma",
    rationale: "3 Serie A titles, 9 Coppa Italia titles, 2023 Europa Conference League finalists. Passionate Curva Sud following. Lazio (2 scudetti) is the historic cross-town rival.",
  },
  {
    rank: 50,
    metro: "Delhi",
    sport: "T20 Cricket",
    team: "Delhi Capitals",
    rationale: "No IPL title but 3 playoff finals and consistent contention. Delhi has produced more Indian Test legends (Kohli, Sehwag, Gambhir) than titles. No dominant football or other team.",
  },
  {
    rank: 51,
    metro: "Johannesburg",
    sport: "Football",
    team: "Mamelodi Sundowns",
    rationale: "South Africa's most successful modern club — 14 PSL titles (including 7 straight 2018-2024), 2016 CAF Champions League winners. Kaizer Chiefs has the largest fanbase on the continent; Orlando Pirates is the historic rival — all three defensible.",
  },
  {
    rank: 52,
    metro: "Cairo",
    sport: "Football",
    team: "Al-Ahly",
    rationale: "Most decorated football club in African history — 45 Egyptian Premier League titles, 12 CAF Champions League titles (most ever). CAF Club of the Century. Zamalek is the rival but Al-Ahly stands alone.",
  },
  {
    rank: 53,
    metro: "Montreal",
    sport: "Hockey",
    team: "Montreal Canadiens",
    rationale: "24 Stanley Cups — the most in NHL history, the most of any North American major-league franchise. The most historically decorated hockey club in the world.",
  },
  {
    rank: 54,
    metro: "San Diego",
    sport: "Baseball",
    team: "San Diego Padres",
    rationale: "No World Series titles but current MLB contender with the Tatis Jr./Machado core. Chargers left for LA; Padres are now the sole major-league team.",
  },
  {
    rank: 55,
    metro: "Vancouver",
    sport: "Hockey",
    team: "Vancouver Canucks",
    rationale: "No Stanley Cup but 3 Finals appearances (1982, 1994, 2011). Vancouver Whitecaps FC (MLS) and BC Lions (CFL) trail in profile.",
  },
  {
    rank: 56,
    metro: "Wuhan",
    sport: "Football",
    team: "Wuhan Three Towns",
    rationale: "2022 Chinese Super League champions — surprise title in debut CSL season. Metro's current football standard-bearer.",
  },
  {
    rank: 57,
    metro: "Denver",
    sport: "American Football",
    team: "Denver Broncos",
    rationale: "3 Super Bowl titles (1997, 1998, 2015), Elway/Manning quarterback heritage, consistently sold-out Mile High since the 1970s — Denver's cultural signature franchise. Nuggets (2023 NBA title) and Avalanche (3 Cups incl. 2022) are both strong modern alternatives.",
  },
  {
    rank: 58,
    metro: "Taipei",
    sport: "Baseball",
    team: "Rakuten Monkeys",
    rationale: "4 consecutive Taiwan Series titles 2017-2019 (as Lamigo and Rakuten). Baseball > basketball in Taiwan; CTBC Brothers are the cross-league rival.",
  },
  {
    rank: 59,
    metro: "Stockholm",
    sport: "Football",
    team: "AIK",
    rationale: "12 Allsvenskan titles — tied-most in Stockholm with Djurgårdens IF. Hammarby has Stockholm's largest fanbase but only 1 title. AIK edges on historical pedigree.",
  },
  {
    rank: 60,
    metro: "Hangzhou",
    sport: "Football",
    team: "Zhejiang Professional FC",
    rationale: "Promoted to CSL in recent years, metro's primary football club. Hangzhou also hosted the 2022 Asian Games — strong event profile but no dominant sports franchise.",
  },
  {
    rank: 61,
    metro: "Lisbon",
    sport: "Football",
    team: "Benfica",
    rationale: "38 Portuguese top-flight titles (most ever), 2 European Cups (1961, 1962), Estádio da Luz is Portugal's biggest stadium. Sporting CP (20 titles) is cross-town rival — Benfica edges on European history.",
  },
  {
    rank: 62,
    metro: "Las Vegas",
    sport: "Hockey",
    team: "Vegas Golden Knights",
    rationale: "2023 Stanley Cup champions in just their 6th season — most successful expansion franchise in modern sports history. Raiders (3 SBs as Oakland/LA) are the NFL presence but Knights own Vegas.",
  },
  {
    rank: 63,
    metro: "Detroit",
    sport: "Hockey",
    team: "Detroit Red Wings",
    rationale: "11 Stanley Cups (3rd-most in NHL), 'Hockeytown USA,' Yzerman/Lidström dynasty 1997-2008. Pistons (3 NBA titles) and Tigers (4 WS) follow.",
  },
  {
    rank: 64,
    metro: "Rio de Janeiro",
    sport: "Football",
    team: "Flamengo",
    rationale: "8 Brasileirão titles, 3 Copa Libertadores (1981, 2019, 2022), largest fanbase in the Americas (40M+). Fluminense (2023 Libertadores), Vasco, Botafogo (2024 Libertadores + Brasileirão) all historic — Flamengo dominates by scale.",
  },
  {
    rank: 65,
    metro: "Minneapolis",
    sport: "American Football",
    team: "Minnesota Vikings",
    rationale: "4 Super Bowl appearances (no wins), one of NFL's most followed franchises. Twins (2 WS) and Timberwolves (2024 Conference Finals) trail — none of MSP's teams dominate like the Vikings in mindshare.",
  },
  {
    rank: 66,
    metro: "Riyadh",
    sport: "Football",
    team: "Al-Hilal",
    rationale: "Asia's most successful football club — 19 Saudi Pro League titles (most ever), 4 AFC Champions League titles (most ever). Home of the Neymar-era Saudi football boom. Al-Nassr (Ronaldo) is cross-town peer.",
  },
  {
    rank: 68,
    metro: "Xi'an",
    sport: "Football",
    team: "Shaanxi Chang'an Union",
    rationale: "Metro lacks a CSL club; Chang'an Union plays in China League One. Xi'an's sports profile is thin.",
  },
  {
    rank: 69,
    metro: "Changsha",
    sport: "Football",
    team: "Hunan Billows",
    rationale: "Lower-division football side. Metro has no top-tier professional sports franchise of note.",
  },
  {
    rank: 70,
    metro: "Abu Dhabi",
    sport: "Football",
    team: "Al Ain FC",
    rationale: "Most successful Emirati club — 14 UAE Pro League titles (most ever), 2003 AFC Champions League winners (only UAE club to win Asia). Al-Jazira (Abu Dhabi city) is the local rival but Al-Ain dominates.",
  },
  {
    rank: 71,
    metro: "Doha",
    sport: "Football",
    team: "Al-Sadd",
    rationale: "17 Qatar Stars League titles (most ever), 2 AFC Champions League titles (1989, 2011), Xavi's post-Barcelona coaching home. Qatar's flagship club.",
  },
  {
    rank: 72,
    metro: "Busan-Ulsan",
    sport: "Football",
    team: "Ulsan Hyundai Horang-i",
    rationale: "5 K League titles including the 2022-2024 three-peat. 2 AFC Champions League titles (2012, 2020). Korea's current dominant football club.",
  },
  {
    rank: 73,
    metro: "Tianjin",
    sport: "Football",
    team: "Tianjin Tigers",
    rationale: "Tianjin Teda/Tianjin FC won a Chinese Cup but no top-flight title. Tianjin Pioneers (CBA) exist. Metro lacks a consistently dominant team.",
  },
  {
    rank: 74,
    metro: "Rotterdam-The Hague",
    sport: "Football",
    team: "Feyenoord",
    rationale: "16 Eredivisie titles, 1970 European Cup, 1974 & 2002 UEFA Cup — one of Netherlands' 'Big 3.' De Kuip is legendary.",
  },
  {
    rank: 75,
    metro: "Copenhagen",
    sport: "Football",
    team: "FC København",
    rationale: "15 Danish Superliga titles, only Danish club with sustained Champions League group-stage presence. Parken Stadium home.",
  },
  {
    rank: 76,
    metro: "Manchester",
    sport: "Football",
    team: "Manchester United",
    rationale: "20 English top-flight titles (joint-most with Liverpool), 3 UEFA Champions League titles, 1999 treble — one of the most supported and valuable sports franchises on earth. Manchester City (8 Premier League titles incl. 2023 treble) is currently superior on the pitch and a defensible co-#1.",
  },
  {
    rank: 77,
    metro: "Tel-Aviv",
    sport: "Basketball",
    team: "Maccabi Tel Aviv BC",
    rationale: "6 Euroleague titles (most by any non-Spanish/Russian club), Israel's most successful sports franchise. In football, Maccabi Tel Aviv FC has 26 Israeli titles.",
  },
  {
    rank: 78,
    metro: "Qingdao",
    sport: "Football",
    team: "Qingdao Hainiu",
    rationale: "Metro's current CSL side, no top-flight titles. Qingdao has historic football roots but no dominant franchise.",
  },
  {
    rank: 79,
    metro: "Phoenix",
    sport: "Basketball",
    team: "Phoenix Suns",
    rationale: "3 NBA Finals appearances (1976, 1993, 2021), no title but the most historically prominent and consistently supported Phoenix franchise. Diamondbacks (2001 WS) have the only major championship; Cardinals still Super Bowl-less.",
  },
  {
    rank: 80,
    metro: "Athens",
    sport: "Football",
    team: "Olympiacos Athens",
    rationale: "48 Greek Super League titles (most ever), 2024 UEFA Europa Conference League champions — first Greek club to win a European trophy. Panathinaikos is the cross-town rival (20 titles). In basketball, Panathinaikos BC (7 Euroleague titles, most in Greek sport) is an equal claimant.",
  },
  {
    rank: 81,
    metro: "St. Louis",
    sport: "Baseball",
    team: "St. Louis Cardinals",
    rationale: "11 World Series titles (2nd-most in MLB after Yankees), most consistent NL franchise. Blues (2019 Cup) are secondary; Rams left for LA.",
  },
  {
    rank: 82,
    metro: "Zurich",
    sport: "Football",
    team: "Grasshopper-Club Zürich",
    rationale: "27 Swiss titles (most ever). FC Zürich has 13 titles and is the modern presence. Grasshopper edges historically.",
  },
  {
    rank: 83,
    metro: "Pittsburgh",
    sport: "American Football",
    team: "Pittsburgh Steelers",
    rationale: "6 Super Bowl titles (tied-most in NFL), Steel Curtain/Terrible Towel culture. Penguins (5 Cups incl. 2016/2017 back-to-back) have near-equal claim. Pirates (5 WS) historic but dormant.",
  },
  {
    rank: 84,
    metro: "Austin",
    sport: "American Football (NCAA)",
    team: "Texas",
    rationale: "4 college football national championships (1963, 1969, 1970, 2005), 2024 and 2025 College Football Playoff semifinalists, most valuable college athletics program in the Big 12/SEC orbit. Darrell K Royal–Texas Memorial Stadium packs 100,000+ in the heart of Austin. The Longhorns dwarf Austin FC (metro's only MLS side) in history, fanbase, and cultural footprint — UT is synonymous with Austin itself.",
  },
  {
    rank: 85,
    metro: "Nagoya",
    sport: "Baseball",
    team: "Chunichi Dragons",
    rationale: "2 Japan Series titles (1954, 2007), 9 Central League titles, one of NPB's historic franchises. Nagoya Grampus (J1, 2 titles) complements.",
  },
  {
    rank: 86,
    metro: "New Orleans",
    sport: "American Football",
    team: "New Orleans Saints",
    rationale: "Super Bowl XLIV champions (2009) — Drew Brees era, the soul of post-Katrina recovery. Pelicans (NBA) and Zion era trail far behind.",
  },
  {
    rank: 87,
    metro: "Warsaw",
    sport: "Football",
    team: "Legia Warszawa",
    rationale: "15 Polish top-flight titles (most ever), only Polish club to reach the UCL group stage multiple times in the modern era.",
  },
  {
    rank: 88,
    metro: "Portland",
    sport: "Basketball",
    team: "Portland Trail Blazers",
    rationale: "1977 NBA champions (Bill Walton era), 3 Finals appearances, the defining franchise in Rip City with a decades-long sellout streak at the Rose Garden/Moda Center. Portland Thorns (3 NWSL titles) and Timbers (2015 MLS Cup) are the modern trophy-getters but the Blazers own the city.",
  },
  {
    rank: 89,
    metro: "Dublin",
    sport: "Rugby Union",
    team: "Leinster",
    rationale: "4 Heineken Champions Cup titles (2009, 2011, 2012, 2018), 9 URC/Pro14/Celtic League titles — by far the most decorated professional sports franchise based in Dublin and one of the most successful rugby clubs in Europe. Shamrock Rovers (21 League of Ireland titles) and Dublin GAA (31 All-Ireland SFC titles) are the football/Gaelic games alternatives.",
  },
  {
    rank: 90,
    metro: "Hamburg",
    sport: "Football",
    team: "Hamburger SV",
    rationale: "6 German top-flight titles, 1983 European Cup, 1977 Cup Winners' Cup — Bundesliga founder member (relegated since 2018). FC St. Pauli is the cult alternative.",
  },
  {
    rank: 91,
    metro: "Brisbane",
    sport: "Rugby League",
    team: "Brisbane Broncos",
    rationale: "6 NRL premierships — most by any Queensland club, most successful franchise north of Sydney. Brisbane Lions (3 AFL premierships, 2001-03 three-peat) are an equal alternative.",
  },
  {
    rank: 92,
    metro: "Calcutta",
    sport: "Football",
    team: "Mohun Bagan",
    rationale: "Indian football's most iconic club — 32+ national titles across formats, 2023 and 2024 ISL Shield winners, 1911 IFA Shield victory a national symbol. East Bengal FC is the cross-town rival.",
  },
  {
    rank: 93,
    metro: "Tampa",
    sport: "American Football",
    team: "Tampa Bay Buccaneers",
    rationale: "2 Super Bowl titles (2002, 2020) — Super Bowl LV won at home with Tom Brady in his first post-Patriots season, becoming the first team to win the SB in its own stadium. Consistent NFC South force in the Mayfield/Baker era. Tampa Bay Lightning (3 Stanley Cups incl. 2020-21 back-to-back) have the modern dynasty claim; Rays (2 WS appearances) have no titles. Buccaneers remain the metro's signature franchise.",
  },
  {
    rank: 94,
    metro: "Cleveland",
    sport: "American Football",
    team: "Cleveland Browns",
    rationale: "4 NFL Championships (1950, 1954, 1955, 1964) — all pre-Super Bowl era. No Super Bowl appearance but the emotional heart of the city: Dawg Pound, Jim Brown, Bernie Kosar, the Drive and the Fumble. Cavaliers (2016 NBA title) have the only major Cleveland championship in 60 years but the Browns own the city's soul.",
  },
  {
    rank: 95,
    metro: "Santiago",
    sport: "Football",
    team: "Colo-Colo FR",
    rationale: "Most successful Chilean club — 34 Chilean Primera División titles (most ever), 1991 Copa Libertadores champion (only Chilean club to win it). National institution.",
  },
  {
    rank: 96,
    metro: "Charlotte",
    sport: "American Football",
    team: "Carolina Panthers",
    rationale: "2 Super Bowl appearances (no wins). Hornets (NBA) have never won. Panthers are Charlotte's biggest franchise despite no championship.",
  },
  {
    rank: 97,
    metro: "Prague",
    sport: "Football",
    team: "AC Sparta Praha",
    rationale: "37+ Czech/Czechoslovak league titles (most ever). Slavia Prague is the cross-town rival. Sparta edges historically.",
  },
  {
    rank: 98,
    metro: "Stuttgart",
    sport: "Football",
    team: "VfB Stuttgart",
    rationale: "5 Bundesliga titles (most recent 2007), historic founder of German football. 2023-24 Bundesliga runner-up.",
  },
  {
    rank: 99,
    metro: "Raleigh-Durham",
    sport: "Basketball (NCAA)",
    team: "North Carolina / Duke",
    rationale: "North Carolina: 6 NCAA men's basketball national championships (1957, 1982, 1993, 2005, 2009, 2017) — tied for 3rd-most in NCAA history. Dean Smith and Roy Williams dynasties, home of Michael Jordan's 1982 title-winning shot. Duke: 5 NCAA titles (1991, 1992, 2001, 2010, 2015), Coach K's 42-year reign producing the winningest coach in men's college basketball history. Genuinely co-equal — UNC edges on trophy count, Duke on modern-era consistency and the Krzyzewski dynasty. The Tobacco Road rivalry is the defining rivalry in American college sports and arguably the cultural #1 of the entire metro. Carolina Hurricanes (2006 Stanley Cup) are the only major pro franchise.",
  },
  {
    rank: 100,
    metro: "Valencia",
    sport: "Football",
    team: "Valencia",
    rationale: "6 La Liga titles, 2 UEFA Cup/Europa League titles (2004), UCL finalists 2000 and 2001 — Spain's 3rd most decorated club at its peak. Villarreal CF (2021 Europa League) is in the neighboring Castellón metro.",
  },
  {
    rank: 101,
    metro: "Auckland",
    sport: "Rugby League",
    team: "New Zealand Warriors",
    rationale: "New Zealand's only NRL franchise and Auckland's defining professional sports team. No premierships (2002 and 2011 Grand Final runners-up) but one of the most passionately supported clubs in the NRL, with 'Up the Wahs' a nationwide cultural movement during their 2023 playoff run. Auckland FC (A-League, launched 2024) is the emerging football brand; Blues (2024 Super Rugby Pacific champions) are the top rugby union side.",
  },
  {
    rank: 102,
    metro: "Cape Town",
    sport: "Rugby Union",
    team: "Stormers",
    rationale: "2022 United Rugby Championship champions — first southern-hemisphere team to win a major European rugby competition. Cape Town City FC leads in football.",
  },
  {
    rank: 103,
    metro: "Perth",
    sport: "Aussie Rules",
    team: "West Coast Eagles",
    rationale: "4 AFL premierships (1992, 1994, 2006, 2018) — Perth's flagship AFL franchise and the most successful non-Victorian club in league history. Perth Stadium sellouts. Fremantle Dockers remain flagless. Perth Scorchers (5 BBL titles, most ever) is the cricket alternative.",
  },
  {
    rank: 104,
    metro: "Salt Lake City-Provo",
    sport: "Basketball",
    team: "Utah Jazz",
    rationale: "No NBA title but 2 Finals appearances (Malone/Stockton era), metro's signature franchise. Real Salt Lake (2009 MLS Cup) and Utah Hockey Club round out.",
  },
  {
    rank: 105,
    metro: "Tehran",
    sport: "Football",
    team: "Persepolis FC",
    rationale: "15 Iranian top-flight titles (most ever). Esteghlal FC has 10 — the Tehran Derby is one of Asia's biggest. Persepolis edges on recent dominance and continental runs (2018 and 2020 AFC CL finalists).",
  },
  {
    rank: 106,
    metro: "Padua-Venice",
    sport: "Football",
    team: "Venezia",
    rationale: "Metro's current Serie A/B flagship. Historically thin — no metro club has won Serie A. Venezia's 1941 Coppa Italia is the highlight.",
  },
  {
    rank: 107,
    metro: "St. Petersburg",
    sport: "Football",
    team: "Zenit St. Petersburg",
    rationale: "10 Russian Premier League titles (including 6 straight 2019-2024), 2008 UEFA Cup, 2008 UEFA Super Cup — Russia's dominant modern club.",
  },
  {
    rank: 108,
    metro: "Nashville",
    sport: "American Football",
    team: "Tennessee Titans",
    rationale: "Super Bowl XXXIV appearance (2000 — 'One Yard Short'), most historically prominent franchise. Predators (NHL Finals 2017) and Nashville SC (MLS) follow.",
  },
  {
    rank: 109,
    metro: "Budapest",
    sport: "Football",
    team: "Ferencvárosi TC",
    rationale: "36 Hungarian league titles (most ever), 1965 Inter-Cities Fairs Cup winners. Hungary's flagship football club.",
  },
  {
    rank: 110,
    metro: "Orlando",
    sport: "Basketball",
    team: "Orlando Magic",
    rationale: "No NBA title but 2 Finals appearances (1995, 2009). Orlando City SC (MLS) and Orlando Pride (NWSL, 2024 champions) round out. Magic remain the metro's signature franchise.",
  },
  {
    rank: 111,
    metro: "Calgary",
    sport: "Hockey",
    team: "Calgary Flames",
    rationale: "1989 Stanley Cup champions, 2004 Finals. Calgary Stampeders (8 Grey Cups in CFL, most recent 2018) are historically more decorated on trophies.",
  },
  {
    rank: 112,
    metro: "Shenyang",
    sport: "Basketball",
    team: "Liaoning Flying Leopards",
    rationale: "3 CBA titles (2018, 2019, 2022), one of Chinese basketball's historic franchises. Metro lacks top-tier CSL football.",
  },
  {
    rank: 113,
    metro: "Indianapolis",
    sport: "American Football",
    team: "Indianapolis Colts",
    rationale: "2 Super Bowl titles (1971 as Baltimore, 2007 Manning era). Pacers (3 ABA titles pre-merger, 2024 NBA Finals) have strong basketball claim. The Indianapolis 500 is bigger than any team.",
  },
  {
    rank: 114,
    metro: "Edinburgh",
    sport: "Football",
    team: "Heart of Midlothian / Hibernian",
    rationale: "4 Scottish league titles. Hibernian has 4 titles too. Neither has won since the 1950s — Edinburgh Rugby (URC) is a modern alternative.",
  },
  {
    rank: 115,
    metro: "Kansas City",
    sport: "American Football",
    team: "Kansas City Chiefs",
    rationale: "4 Super Bowl titles (1969, 2019, 2022, 2023) — current NFL dynasty with Mahomes/Reid. Back-to-back 2022 and 2023. Royals (2 WS) trail.",
  },
  {
    rank: 116,
    metro: "Bogota",
    sport: "Football",
    team: "Millonarios",
    rationale: "16 Categoría Primera A titles (tied with Atlético Nacional for most in Colombia). Independiente Santa Fe (9 titles) is the cross-town rival.",
  },
  {
    rank: 117,
    metro: "Dalian",
    sport: "Football",
    team: "Dalian Yifang",
    rationale: "Metro's current CSL side. Dalian Shide was CSL's historic dynasty (8 titles 1994-2005) but is now defunct. Yifang is the successor franchise.",
  },
  {
    rank: 118,
    metro: "Jeddah",
    sport: "Football",
    team: "Al-Ittihad",
    rationale: "9 Saudi Pro League titles, 2 AFC Champions League titles (2004, 2005 — first Saudi club to win Asia). 2022-23 SPL champions with Benzema/Kanté era.",
  },
  {
    rank: 119,
    metro: "Xiamen",
    sport: "Football",
    team: "Xiamen Blue Lions",
    rationale: "Lower-division football side. No CSL presence. Metro lacks a top-tier pro sports franchise.",
  },
  {
    rank: 120,
    metro: "Lyon",
    sport: "Football",
    team: "Olympique Lyonnais",
    rationale: "7 Ligue 1 titles (7 consecutive 2002-2008). OL Féminin has won 8 UEFA Women's Champions League titles (most ever). Men's side historically dominant in France behind only PSG.",
  },
  {
    rank: 121,
    metro: "Macau",
    sport: "Football",
    team: "Benfica (Macau)",
    rationale: "Multiple Liga de Elite titles. Macau's top-flight football is thin; metro's sporting identity is primarily casino/events-based.",
  },
  {
    rank: 122,
    metro: "Zhengzhou",
    sport: "Football",
    team: "Henan Songshan Longmen",
    rationale: "Metro's CSL side (formerly Henan Jianye). No titles. Thin sports profile.",
  },
  {
    rank: 123,
    metro: "Naples",
    sport: "Football",
    team: "SSC Napoli",
    rationale: "3 Serie A titles (1987, 1990, 2023) — the Maradona-era legends and the Kvaratskhelia/Osimhen-era champs. Cultural institution beyond sports.",
  },
  {
    rank: 124,
    metro: "Turin",
    sport: "Football",
    team: "Juventus",
    rationale: "36 Serie A titles (most ever, though 2 stripped), 2 UEFA Champions League titles (1985, 1996), Italy's most decorated and most supported club. Torino FC (7 scudetti, Grande Torino) is cross-town.",
  },
  {
    rank: 125,
    metro: "Ho Chi Minh City",
    sport: "Football",
    team: "Ho Chi Minh City FC",
    rationale: "Vietnam's top-tier metro club, multiple national titles historically. Thinner presence than Hanoi FC nationally.",
  },
  {
    rank: 126,
    metro: "Hefei",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise of note in metro.",
  },
  {
    rank: 127,
    metro: "Marseille",
    sport: "Football",
    team: "Olympique Marseille",
    rationale: "10 Ligue 1 titles, 1993 UEFA Champions League — only French club to win the UCL. Velodrome fanbase among France's most passionate.",
  },
  {
    rank: 128,
    metro: "Geneva",
    sport: "Hockey",
    team: "Genève-Servette HC",
    rationale: "2023 Swiss National League champions and 2024 Champions Hockey League winners. Servette FC (17 Swiss football titles) has more historic weight but the hockey side is the current force.",
  },
  {
    rank: 129,
    metro: "Oslo",
    sport: "Hockey",
    team: "Vålerenga Ishockey",
    rationale: "6 Norwegian ice hockey championships — Oslo's most consistently successful top-flight team across any sport. Vålerenga's football side (Eliteserien, 5 titles) is the historical alternative, but Norway's national football weight sits with Rosenborg (Trondheim). Hockey is Oslo's stronger claim.",
  },
  {
    rank: 130,
    metro: "Porto",
    sport: "Football",
    team: "FC Porto",
    rationale: "30 Primeira Liga titles, 2 UEFA Champions League titles (1987, 2004), 2 UEFA Cup/Europa League titles (2003, 2011) — Mourinho's launchpad. Portugal's 2nd most decorated club.",
  },
  {
    rank: 131,
    metro: "Birmingham",
    sport: "Football",
    team: "Aston Villa",
    rationale: "7 English league titles and 1982 European Cup (underrated European pedigree). Birmingham City (League Cup 2011) and West Brom are other clubs — Villa clearly #1.",
  },
  {
    rank: 132,
    metro: "Jinan",
    sport: "Football",
    team: "Shandong Taishan",
    rationale: "5 CSL titles (most in Chinese Super League era), 9 Chinese FA Cups. One of China's consistently dominant football clubs.",
  },
  {
    rank: 133,
    metro: "Nairobi",
    sport: "Football",
    team: "Gor Mahia",
    rationale: "20 Kenyan Premier League titles (most ever), 1987 CAF Cup Winners' Cup winners. Kenya's flagship football club. AFC Leopards is the cross-town rival.",
  },
  {
    rank: 134,
    metro: "Liverpool",
    sport: "Football",
    team: "Liverpool",
    rationale: "20 English top-flight titles (tied-most with Man United), 6 UEFA Champions League titles (most of any English club). Everton (9 English titles) is the historic cross-town rival.",
  },
  {
    rank: 135,
    metro: "Helsinki",
    sport: "Football",
    team: "HJK Helsinki",
    rationale: "33 Finnish top-flight titles (most ever), only Finnish club to regularly compete in European group stages. HIFK is the cross-town rival.",
  },
  {
    rank: 136,
    metro: "Cincinnati",
    sport: "Baseball",
    team: "Cincinnati Reds",
    rationale: "5 World Series titles including the Big Red Machine 1975-76 back-to-back. Bengals (3 SB appearances, no wins) have more mindshare today but Reds have the trophies. FC Cincinnati (2023 Supporters' Shield) growing.",
  },
  {
    rank: 137,
    metro: "Hanoi",
    sport: "Football",
    team: "Hanoi FC",
    rationale: "6 V.League 1 titles (most ever in the modern era), Vietnam's dominant football club of the 2010s-20s.",
  },
  {
    rank: 138,
    metro: "Lima",
    sport: "Football",
    team: "Universitario",
    rationale: "28 Peruvian Primera titles (most ever). Alianza Lima (25 titles) is the fierce cross-town rival — Peru's biggest derby. Universitario edges on total titles.",
  },
  {
    rank: 139,
    metro: "Hannover-Brunswick",
    sport: "Football",
    team: "Hannover 96",
    rationale: "2 German league titles (1938, 1954). Eintracht Braunschweig won the 1967 Bundesliga. Both in lower divisions currently.",
  },
  {
    rank: 140,
    metro: "Basel",
    sport: "Football",
    team: "FC Basel",
    rationale: "20 Swiss Super League titles (2nd-most), sustained UEFA Champions League group-stage presence in the 2010s. St. Jakob-Park modern venue.",
  },
  {
    rank: 141,
    metro: "Lausanne",
    sport: "Football",
    team: "Lausanne-Sports",
    rationale: "7 Swiss football titles. Lausanne HC (hockey) is rising. Neither dominant currently.",
  },
  {
    rank: 142,
    metro: "Glasgow",
    sport: "Football",
    team: "Celtic / Rangers",
    rationale: "Celtic: 54 Scottish league titles, 1967 European Cup (Lisbon Lions — first British club to win Europe), 40 Scottish Cups. Rangers: 55 Scottish league titles (most ever in Scottish football), 1972 UEFA Cup Winners' Cup, 34 Scottish Cups. Genuinely co-equal — Rangers edge by one title (55 vs 54), Celtic edge on European Cup pedigree and modern dominance. The Old Firm is one of world sport's most intense rivalries and the two clubs together have won more than 110 of Scotland's ~130 league titles. Between them they define Glasgow sport entirely.",
  },
  {
    rank: 143,
    metro: "Nanning",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise of note.",
  },
  {
    rank: 144,
    metro: "Ningbo",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise of note; metro lacks CSL/CBA presence.",
  },
  {
    rank: 145,
    metro: "Antwerp",
    sport: "Football",
    team: "Royal Antwerp FC",
    rationale: "2023 Belgian Pro League champions (first title in 66 years), Belgium's oldest club (1880). 4 Belgian titles total.",
  },
  {
    rank: 146,
    metro: "Kuwait City",
    sport: "Football",
    team: "Al-Kuwait",
    rationale: "19 Kuwaiti Premier League titles (most ever), 2 AFC Cups (2009, 2012). Kuwait's flagship club.",
  },
  {
    rank: 147,
    metro: "Fuzhou",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise of note.",
  },
  {
    rank: 148,
    metro: "Baku",
    sport: "Football",
    team: "FK Karabakh",
    rationale: "11 Azerbaijan Premier League titles (most ever), regular UEFA Champions League group-stage and Europa League qualifier. Azerbaijan's flagship club.",
  },
  {
    rank: 149,
    metro: "Panama City",
    sport: "Football",
    team: "Tauro FC",
    rationale: "12 Panamanian Primera titles (most ever). Panama's top-flight is thin globally.",
  },
  {
    rank: 150,
    metro: "Florence",
    sport: "Football",
    team: "Fiorentina",
    rationale: "2 Serie A titles (1956, 1969), 1961 Cup Winners' Cup, 6 Coppa Italia titles, back-to-back Europa Conference League finalists (2023, 2024). Passionate Viola fanbase.",
  },
  {
    rank: 151,
    metro: "Ottawa",
    sport: "Hockey",
    team: "Ottawa Senators",
    rationale: "Stanley Cup Finals appearance in 2007. Historic Ottawa Senators franchise (separate entity) won 11 Stanley Cups 1903-1927. Ottawa Redblacks (CFL, 2016 Grey Cup) secondary.",
  },
  {
    rank: 152,
    metro: "Kunming",
    sport: "",
    team: "—",
    rationale: "No CSL side. Thin professional sports profile.",
  },
  {
    rank: 153,
    metro: "Nice",
    sport: "Football",
    team: "OGC Nice",
    rationale: "4 Ligue 1 titles (all 1950s), regular top-half Ligue 1 finisher. Allianz Riviera modern stadium.",
  },
  {
    rank: 154,
    metro: "Harbin",
    sport: "",
    team: "—",
    rationale: "No CSL/CBA top-tier team. Regional ice hockey only.",
  },
  {
    rank: 155,
    metro: "Ankara",
    sport: "Football",
    team: "Gençlerbirliği",
    rationale: "2 Turkish Cups (1987, 2001). MKE Ankaragücü also competes. Metro lacks a Süper Lig title despite being the capital.",
  },
  {
    rank: 156,
    metro: "Nanchang",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise of note.",
  },
  {
    rank: 157,
    metro: "Columbus",
    sport: "American Football (NCAA)",
    team: "Ohio State",
    rationale: "8 national championships in college football (including 2024 CFP title), 41 Big Ten titles, the most valuable college athletics program in America. Ohio Stadium ('The Horseshoe') packs 102,000+. Columbus Crew (3 MLS Cups) is the top pro franchise but Ohio State is the cultural center of Columbus and the state.",
  },
  {
    rank: 158,
    metro: "Monterrey",
    sport: "Football",
    team: "Monterrey",
    rationale: "5 Liga MX titles, 6 CONCACAF Champions League titles (most ever, including 2025). Northern Mexico's powerhouse. Tigres UANL (cross-metro San Nicolás) is an equal rival with 5 Liga MX titles.",
  },
  {
    rank: 159,
    metro: "Milwaukee",
    sport: "American Football",
    team: "Green Bay Packers",
    rationale: "13 NFL championships (most in NFL history) including 4 Super Bowl titles. Green Bay sits 2 hours north of Milwaukee, but the Packers are Wisconsin's statewide team — they play preseason games at Lambeau in front of a Milwaukee-heavy crowd, and Milwaukee is the state's largest market and single biggest ticket base. The Packers own Wisconsin identity in a way the Bucks (2 NBA titles) and Brewers (no WS) do not. Strongest 'nearby team' case in American sports.",
  },
  {
    rank: 160,
    metro: "Dhaka",
    sport: "Test Cricket",
    team: "Bangladesh National Cricket Team",
    rationale: "Cricket is Bangladesh's national sport by a massive margin, and the Tigers are the country's defining sporting institution — Full Member status with the ICC since 2000, 2015 and 2019 ICC Cricket World Cup quarter-finalists, 2012 Asia Cup finalists, and home Test matches at Sher-e-Bangla National Cricket Stadium in Mirpur (Dhaka). Shakib Al Hasan, Tamim Iqbal, and Mushfiqur Rahim generation elevated the program to consistent international relevance. Bashundhara Kings (Bangladesh Premier League football, 5 titles since 2019) and Dhaka Abahani are the top club sides but cricket is what Dhaka cares about.",
  },
  {
    rank: 161,
    metro: "Manama",
    sport: "Football",
    team: "Al-Muharraq Club",
    rationale: "36+ Bahraini Premier League titles (most ever). Bahrain's dominant football club.",
  },
  {
    rank: 162,
    metro: "Fukuoka",
    sport: "Baseball",
    team: "Fukuoka SoftBank Hawks",
    rationale: "11 Japan Series titles (2nd-most in NPB), including 4 in 5 years 2014-2020. Current Pacific League power. Avispa Fukuoka (J1) secondary.",
  },
  {
    rank: 163,
    metro: "Sacramento",
    sport: "Basketball",
    team: "Sacramento Kings",
    rationale: "1 NBA title (1951 as Rochester Royals), no Finals since 2002. Only major-league franchise in metro.",
  },
  {
    rank: 164,
    metro: "Colombo",
    sport: "T20 Cricket",
    team: "Jaffna Kings",
    rationale: "3 Lanka Premier League titles (most ever). Colombo Strikers is the metro's home side. Sri Lankan football is thin globally; cricket dominates.",
  },
  {
    rank: 165,
    metro: "Bangalore",
    sport: "T20 Cricket",
    team: "Royal Challengers Bengaluru",
    rationale: "2025 IPL champions — first title after 18 years of near-misses, Virat Kohli's franchise. Massive global IPL fanbase. Bengaluru FC (3 ISL Shields, 2019 ISL Cup) strong in football.",
  },
  {
    rank: 166,
    metro: "Jacksonville",
    sport: "American Football",
    team: "Jacksonville Jaguars",
    rationale: "No Super Bowl appearances but 3 AFC Championship appearances. Only major-league franchise in metro.",
  },
  {
    rank: 167,
    metro: "Guadalajara",
    sport: "Football",
    team: "Guadalajara",
    rationale: "12 Liga MX titles (2nd-most in Mexico), 2018 CONCACAF Champions League winners. One of Mexico's 'Big Four' with an all-Mexican player policy — unique in world football. Atlas (cross-town, 2021/2022 titles) broke a long drought.",
  },
  {
    rank: 168,
    metro: "Bilbao",
    sport: "Football",
    team: "Athletic Bilbao",
    rationale: "8 La Liga titles, 24 Copa del Rey titles (2nd-most, including 2024 after a 40-year drought). Famous Basque-only recruitment policy — unique in modern football.",
  },
  {
    rank: 169,
    metro: "Guiyang",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise.",
  },
  {
    rank: 170,
    metro: "Taichung",
    sport: "Baseball",
    team: "CTBC Brothers",
    rationale: "11 Taiwan Series titles (most ever in CPBL). Metro's dominant franchise — baseball is the dominant sport in Taichung.",
  },
  {
    rank: 171,
    metro: "Louisville",
    sport: "Basketball (NCAA)",
    team: "Louisville",
    rationale: "3 NCAA basketball titles (1980, 1986, 2013 — last vacated). Culturally dominant franchise. Louisville City FC won back-to-back USL Championship titles (2017, 2018). The Kentucky Derby is bigger than any team.",
  },
  {
    rank: 172,
    metro: "Changchun",
    sport: "Football",
    team: "Changchun YaTai",
    rationale: "2007 CSL champions. Metro's primary CSL side currently, no recent silverware.",
  },
  {
    rank: 173,
    metro: "Shijiazhuang",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise.",
  },
  {
    rank: 174,
    metro: "Haikou",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise.",
  },
  {
    rank: 175,
    metro: "Belgrade",
    sport: "Football",
    team: "Red Star Belgrade",
    rationale: "33+ Serbian/Yugoslav top-flight titles, 1991 European Cup winners and 1991 Intercontinental Cup champions — only Serbian/Yugoslav club to win Europe. Partizan Belgrade (27 titles) is the cross-town rival.",
  },
  {
    rank: 176,
    metro: "Lanzhou",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise.",
  },
  {
    rank: 177,
    metro: "Hyderabad",
    sport: "T20 Cricket",
    team: "Sunrisers Hyderabad",
    rationale: "1 IPL title (2016). Consistent playoff contender, 2024 IPL finalists. Hyderabad FC (2021-22 ISL Cup winners) complements.",
  },
  {
    rank: 178,
    metro: "Omaha-Lincoln",
    sport: "American Football (NCAA)",
    team: "Nebraska",
    rationale: "5 national championships in college football (1970, 1971, 1994, 1995, 1997). Memorial Stadium sellout streak since 1962. No major-league pro teams in metro.",
  },
  {
    rank: 179,
    metro: "Chennai",
    sport: "T20 Cricket",
    team: "Chennai Super Kings",
    rationale: "5 IPL titles (tied-most with Mumbai Indians — won 2010, 2011, 2018, 2021, 2023), MS Dhoni's yellow army — one of the IPL's defining franchises globally. Chennaiyin FC (2 ISL Cups) secondary.",
  },
  {
    rank: 180,
    metro: "Lagos",
    sport: "Football",
    team: "MFM FC",
    rationale: "Nigeria's club football centers of gravity are Enyimba (Aba) and Kano Pillars — Lagos clubs like MFM, Sporting Lagos, and Remo Stars compete in the NPFL but none dominate nationally. Lagos's sporting identity is lighter on dominant clubs than its size suggests.",
  },
  {
    rank: 181,
    metro: "Seville",
    sport: "Football",
    team: "Sevilla FC",
    rationale: "1 La Liga title (1946) but 7 UEFA Europa League / UEFA Cup titles (most ever, by a wide margin). Real Betis (1 La Liga, 1935; 3 Copa del Rey incl. 2022) is the cross-town rival.",
  },
  {
    rank: 182,
    metro: "San Antonio",
    sport: "Basketball",
    team: "San Antonio Spurs",
    rationale: "5 NBA titles (1999, 2003, 2005, 2007, 2014) — Duncan/Popovich dynasty, one of the best-run franchises in American sports. The Wembanyama era launching a new chapter.",
  },
  {
    rank: 183,
    metro: "Taiyuan",
    sport: "",
    team: "—",
    rationale: "No top-tier pro franchise.",
  },
  {
    rank: 184,
    metro: "Dammam",
    sport: "Football",
    team: "Al-Ettifaq",
    rationale: "2 Saudi Pro League titles (1983, 1987). Home of the Henderson/Firmino 2023 Saudi boom signings.",
  },
  {
    rank: 185,
    metro: "Rhine-Neckar",
    sport: "Hockey",
    team: "Adler Mannheim",
    rationale: "8 DEL (Deutsche Eishockey Liga) championships (1997, 1998, 1999, 2001, 2007, 2015, 2019, 2023) — tied for most in DEL history. One of German ice hockey's two or three most iconic clubs, playing at the SAP Arena. More titles and higher national profile than Rhein-Neckar Löwen (handball, 2 titles) and TSG 1899 Hoffenheim (Bundesliga football, no titles despite sustained top-flight presence).",
  },
  {
    rank: 186,
    metro: "Daejeon",
    sport: "Baseball",
    team: "Hanwha Eagles",
    rationale: "1999 Korean Series champions. Daejeon Hana Citizen (K League 1) is the football side. Neither nationally dominant.",
  },
  {
    rank: 187,
    metro: "George Town",
    sport: "",
    team: "—",
    rationale: "Penang FC plays in Malaysian lower tier. No top-flight franchise of note.",
  },
  {
    rank: 188,
    metro: "Brasilia",
    sport: "",
    team: "—",
    rationale: "No Série A club. Metro lacks a national-level sports franchise despite being the capital — a Brazilian football quirk.",
  },
  {
    rank: 189,
    metro: "Hiroshima",
    sport: "Baseball",
    team: "Hiroshima Toyo Carp",
    rationale: "3 Japan Series titles, most recently 1984. Passionate fanbase in Mazda Zoom-Zoom Stadium. Sanfrecce Hiroshima has 3 J1 titles in football.",
  },
  {
    rank: 190,
    metro: "Karachi",
    sport: "T20 Cricket",
    team: "Karachi Kings",
    rationale: "1 Pakistan Super League title (2020). Pakistan's biggest T20 franchise by market. Cricket's centrality in Pakistan makes PSL the dominant league.",
  },
  {
    rank: 191,
    metro: "Alexandria",
    sport: "Football",
    team: "Al-Ittihad Al-Sakndary",
    rationale: "Historic Egyptian club but a mid-table side — metro thin on national titles. Cairo clubs (Al-Ahly, Zamalek) dominate Egyptian football.",
  },
  {
    rank: 192,
    metro: "Toulouse",
    sport: "Rugby Union",
    team: "Stade Toulousain",
    rationale: "23 French Top 14 titles (most ever), 6 European Champions Cup titles (most ever, including 2024) — the most decorated club rugby team in Europe. Toulouse FC (Ligue 1, 1957 title, 2023 Coupe de France) secondary.",
  },
  {
    rank: 193,
    metro: "Sapporo",
    sport: "Baseball",
    team: "Hokkaido Nippon-Ham Fighters",
    rationale: "2006 and 2016 Japan Series champions — Shohei Ohtani's launching pad. New Escon Field (2023). Sapporo's current signature franchise.",
  },
  {
    rank: 194,
    metro: "Saxon Triangle",
    sport: "Football",
    team: "RB Leipzig",
    rationale: "Leipzig joined the metro's pro sports scene in 2009 and is now a Bundesliga fixture — 2022 and 2023 DFB-Pokal winners, consistent top-four finisher, regular UEFA Champions League participant. Dynamo Dresden (8 East German titles) is the historic alternative.",
  },
  {
    rank: 195,
    metro: "Johor Bahru",
    sport: "Football",
    team: "Johor Darul Ta'zim",
    rationale: "11 consecutive Malaysia Super League titles (2014-2024) — most dominant club in Malaysian history, first Malaysian club to reach AFC Champions League knockout rounds.",
  },
  {
    rank: 196,
    metro: "Surabaya",
    sport: "Football",
    team: "Persebaya FC",
    rationale: "2 Indonesian top-flight titles. Historic eastern Java giant, passionate Bonek fanbase.",
  },
  {
    rank: 197,
    metro: "Izmir",
    sport: "Football",
    team: "Göztepe AS",
    rationale: "2 Turkish Cups (1969, 1970), 1968-69 Fairs Cup semifinalists. Altay SK is the cross-town rival. Izmir has never won the Süper Lig title.",
  },
  {
    rank: 198,
    metro: "Providence",
    sport: "Basketball (NCAA)",
    team: "Providence",
    rationale: "1973 Final Four appearance, 2 Big East regular-season titles. Culturally dominant college franchise. Providence Bruins (AHL) only pro franchise.",
  },
  {
    rank: 199,
    metro: "Bologna",
    sport: "Football",
    team: "Bologna",
    rationale: "7 Serie A titles (all pre-1965), 2 Mitropa Cups. Historic powerhouse qualified for Champions League 2024-25 under Thiago Motta. 2024 Coppa Italia finalist.",
  },
  {
    rank: 200,
    metro: "Leeds-Bradford",
    sport: "Football",
    team: "Leeds United",
    rationale: "3 English top-flight titles (1969, 1974, 1992), 1968 and 1971 Inter-Cities Fairs Cup winners, 2001 UEFA Champions League semifinalists — historic giant with the Don Revie era. Leeds Rhinos (8 Super League titles) is co-dominant in the metro in rugby league.",
  },
  {
    rank: 203,
    metro: "Montevideo",
    sport: "Football",
    team: "Peñarol / Nacional",
    rationale: "Peñarol: 5 Copa Libertadores (1960, 1961, 1966, 1982, 1987), 3 Intercontinental Cups — among the most decorated clubs in South American history. Nacional: 3 Copa Libertadores, 3 Intercontinental Cups. Two of the 5-6 most historically decorated clubs in South American football.",
  },
  {
    rank: 216,
    metro: "Tunis",
    sport: "Football",
    team: "Espérance",
    rationale: "33 Tunisian league titles (most ever) and 4 CAF Champions League titles (2011, 2018, 2019, 2024) — tied-most in African football history. Continental heavyweight.",
  },
  {
    rank: 218,
    metro: "Thessaloniki",
    sport: "Football",
    team: "PAOK Thessaloniki",
    rationale: "3 Greek Super League titles including the 2018-19 unbeaten title, cult Toumba fanbase. Only Greek club outside Olympiacos/Panathinaikos with modern continental relevance.",
  },
  {
    rank: 221,
    metro: "Kinshasa",
    sport: "Football",
    team: "AS Vita Club",
    rationale: "1973 CAF Champions League winners (first club from DR Congo to win Africa's top continental trophy) and 2014 runners-up. Kinshasa's historic football institution. TP Mazembe (Lubumbashi, ~2,000 km away and separately iconic) is often confused with Kinshasa football but is an entirely different city on the opposite side of the country. DC Motema Pembe (Kinshasa, 1994 CAF Cup Winners' Cup) is the cross-town rival.",
  },
  {
    rank: 224,
    metro: "Salvador",
    sport: "Football",
    team: "EC Bahia",
    rationale: "2 Brasileirão titles (1959, 1988), massive fanbase — one of Brazil's historic regional giants, now in the Grupo City ownership.",
  },
  {
    rank: 228,
    metro: "Addis Ababa",
    sport: "Football",
    team: "Saint George FC",
    rationale: "30 Ethiopian Premier League titles (most ever), Ethiopia's most decorated football club and a regular CAF Champions League participant.",
  },
  {
    rank: 231,
    metro: "Eindhoven",
    sport: "Football",
    team: "PSV Eindhoven",
    rationale: "26 Eredivisie titles (2nd-most after Ajax), 1988 European Cup, 1978 UEFA Cup. Dutch 'Big 3' member alongside Ajax and Feyenoord — a global football name.",
  },
  {
    rank: 241,
    metro: "Monaco",
    sport: "Football",
    team: "AS Monaco",
    rationale: "8 Ligue 1 titles, 2004 UEFA Champions League finalists, 1992 Cup Winners' Cup. Historic incubator of Thierry Henry, Mbappé, George Weah, Fabinho.",
  },
  {
    rank: 253,
    metro: "Knoxville",
    sport: "American Football (NCAA)",
    team: "Tennessee",
    rationale: "6 national championships, Neyland Stadium holds 101,000+ (3rd-largest in college football). 'Rocky Top' and the checkerboard end zones are iconic.",
  },
  {
    rank: 266,
    metro: "Casablanca",
    sport: "Football",
    team: "Wydad Casablanca / Raja Casablanca",
    rationale: "Wydad: 22 Moroccan titles + 3 CAF Champions League titles. Raja: 13 Moroccan titles + 3 CAF Champions Leagues. Casablanca Derby is one of Africa's fiercest; both genuine continental icons.",
  },
  {
    rank: 269,
    metro: "Sofia",
    sport: "Football",
    team: "CSKA Sofia",
    rationale: "CSKA: 31 Bulgarian league titles, 2 European Cup semi-finals (1967, 1982). Levski: 26 Bulgarian titles. Bulgaria's two historic football giants; the Eternal Derby is one of the Balkans' fiercest.",
  },
  {
    rank: 274,
    metro: "Birmingham (AL)",
    sport: "American Football (NCAA)",
    team: "Alabama",
    rationale: "18 college football national championships (most ever), 6 CFP/BCS titles under Nick Saban — the single most dominant dynasty in 21st-century American sports.",
  },
  {
    rank: 284,
    metro: "Kiel",
    sport: "Handball",
    team: "THW Kiel",
    rationale: "22 German Handball Bundesliga titles (most ever), 4 EHF Champions League titles — the most decorated handball club in European history. A true continental giant in its sport.",
  },
  {
    rank: 287,
    metro: "Salzburg",
    sport: "Football",
    team: "FC Red Bull Salzburg",
    rationale: "11 consecutive Austrian Bundesliga titles (2013-2024, most dominant run in Austrian football), regular UCL group-stage participant, and the Red Bull football pipeline (Haaland, Mané, Szoboszlai, etc.).",
  },
  {
    rank: 296,
    metro: "Quito",
    sport: "Football",
    team: "LDU Quito",
    rationale: "2008 Copa Libertadores champions (only Ecuadorian club to win it), 2009 Copa Sudamericana, 2009 Recopa Sudamericana. Ecuador's most internationally successful club.",
  },
  {
    rank: 306,
    metro: "Asunción",
    sport: "Football",
    team: "Olimpia",
    rationale: "3 Copa Libertadores (1979, 1990, 2002), 1979 Intercontinental Cup — Paraguay's lone continental giant, one of South America's historic powers.",
  },
  {
    rank: 323,
    metro: "Minho (Braga)",
    sport: "Football",
    team: "Sporting Braga",
    rationale: "Regular UEFA Champions League and Europa League participant, 2011 Europa League finalists. Portugal's 4th club behind Porto/Benfica/Sporting.",
  },
  {
    rank: 324,
    metro: "Barranquilla",
    sport: "Football",
    team: "Junior",
    rationale: "9 Colombian Primera titles, 3 Copa Libertadores finals appearances. Shakira's hometown club, deeply tied to Colombian football identity.",
  },
  {
    rank: 325,
    metro: "Zagreb",
    sport: "Football",
    team: "Dinamo Zagreb",
    rationale: "26 Croatian league titles (most ever), regular UEFA Champions League group-stage participant. Produced Luka Modrić, Mateo Kovačić, and much of Croatia's 2018 World Cup runner-up squad.",
  },
  {
    rank: 333,
    metro: "Tbilisi",
    sport: "Football",
    team: "Dinamo Tbilisi",
    rationale: "1981 UEFA Cup Winners' Cup champions (only Georgian/Soviet Georgian club to win a major European trophy), 14 Soviet era + 19 Georgian league titles.",
  },
  {
    rank: 344,
    metro: "Abidjan",
    sport: "Football",
    team: "ASEC Mimosas",
    rationale: "28 Ivorian league titles (most ever), 1998 CAF Champions League champions. Academy produced Yaya Touré, Kolo Touré, Didier Zokora, Salomon Kalou — one of Africa's most famous youth pipelines.",
  },
  {
    rank: 355,
    metro: "Lexington",
    sport: "Basketball (NCAA)",
    team: "Kentucky",
    rationale: "8 NCAA men's basketball national championships (most outside UCLA), the winningest program in college basketball by win percentage. Rupp Arena.",
  },
  {
    rank: 356,
    metro: "Trondheim",
    sport: "Football",
    team: "Rosenborg BK",
    rationale: "26 Norwegian league titles (most ever), 13 consecutive titles 1992-2004 — one of the most dominant national runs in European football. Regular UCL group-stage presence in the 1990s-2000s.",
  },
  {
    rank: 357,
    metro: "Accra",
    sport: "Football",
    team: "Hearts of Oak / Asante Kotoko",
    rationale: "Hearts of Oak: 2000 CAF Champions League winners, 21 Ghanaian titles. Asante Kotoko (Kumasi, nearby): 2 CAF Champions Leagues (1970, 1983), 24 Ghanaian titles. Ghana's two continental-champion giants.",
  },
  {
    rank: 365,
    metro: "Baton Rouge",
    sport: "American Football (NCAA)",
    team: "LSU",
    rationale: "4 college football national championships (2003, 2007, 2019 — Joe Burrow's historic season). Tiger Stadium 'Death Valley' is one of the loudest venues in American sports.",
  },
  {
    rank: 367,
    metro: "South Bend",
    sport: "American Football (NCAA)",
    team: "Notre Dame",
    rationale: "11 college football national championships, the only independent program with its own national TV contract (NBC). The most culturally iconic brand in American college sports — Knute Rockne, the Four Horsemen, Touchdown Jesus.",
  },
  {
    rank: 371,
    metro: "Bratislava",
    sport: "Football",
    team: "ŠK Slovan Bratislava",
    rationale: "1969 UEFA Cup Winners' Cup champions (only Slovak/Czechoslovak club ever to win a major European trophy), 15 Slovak titles.",
  },
  {
    rank: 377,
    metro: "Clermont-Ferrand",
    sport: "Rugby Union",
    team: "Clermont",
    rationale: "2 French Top 14 titles (2010, 2017), 3 European Champions Cup finals. One of France's most passionately supported rugby clubs.",
  },
  {
    rank: 388,
    metro: "Poznań",
    sport: "Football",
    team: "Lech Poznan",
    rationale: "8 Polish Ekstraklasa titles, 2022-23 Polish champions. Regular European group-stage participant and home of the globally famous 'Poznań' celebration adopted by Man City and others.",
  },
  {
    rank: 391,
    metro: "La Paz",
    sport: "Football",
    team: "Bolívar",
    rationale: "30 Bolivian league titles (most ever), regular Copa Libertadores participant playing at 3,600m altitude — the highest-altitude major club venue in world football.",
  },
  {
    rank: 397,
    metro: "Greenville-Spartanburg",
    sport: "American Football (NCAA)",
    team: "Clemson",
    rationale: "3 national championships (1981, 2016, 2018), Dabo Swinney's 2010s dynasty, Death Valley and the hill run-out tradition.",
  },
  {
    rank: 410,
    metro: "Tallahassee",
    sport: "American Football (NCAA)",
    team: "Florida State",
    rationale: "3 national championships (1993, 1999, 2013), Bobby Bowden's 377 wins. Doak Campbell Stadium and the Seminole tomahawk chop.",
  },
  {
    rank: 413,
    metro: "Eugene",
    sport: "American Football (NCAA)",
    team: "Oregon",
    rationale: "0 national titles but Phil Knight / Nike's flagship university — most visually recognizable brand in college football via uniform rotation and Autzen Stadium's decibel record.",
  },
  {
    rank: 428,
    metro: "Rosario",
    sport: "Football",
    team: "Newell's Old Boys / Rosario Central",
    rationale: "Newell's: Messi's boyhood club, 6 Argentine league titles, 2 Copa Libertadores finals. Rosario Central: 4 Argentine league titles. The Rosario Derby is globally recognized as one of football's most intense.",
  },
  {
    rank: 433,
    metro: "Christchurch",
    sport: "Rugby Union",
    team: "Crusaders",
    rationale: "14 Super Rugby titles (most ever, by a large margin) — the most decorated franchise in southern-hemisphere rugby. Genuine global rugby name.",
  },
  {
    rank: 439,
    metro: "State College",
    sport: "American Football (NCAA)",
    team: "Penn State",
    rationale: "2 national championships (1982, 1986), Joe Paterno's 409 wins, 107,000-seat Beaver Stadium 'White Out' — one of college sports' most iconic atmospheres.",
  },
  {
    rank: 448,
    metro: "Gainesville",
    sport: "American Football (NCAA)",
    team: "Florida",
    rationale: "3 national championships (1996, 2006, 2008), Tebow/Spurrier era. The Swamp holds 88,500.",
  },
];

export function topTeamAnchorId(metro: string): string {
  return (
    "team-" +
    metro
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
  );
}
