import "server-only";
import { readFileSync } from "fs";
import { join } from "path";

// Women's Football portal data. Generated by
// scripts/build-wfootball-data.py from the "Women's Football" sheet of
// OtherLeagues.xlsx (honors / finals history). Shape mirrors the men's
// European-tournaments hub so the /teams/wfootball pages can reuse the same
// finals-table + most-decorated renderer conventions.

// ─── Types ───────────────────────────────────────────────────────────────────

export type WChampion = {
  year: number;
  cur_name: string;
  slug: string;
  score: string | null;        // match score for cups; null for league titles
  runner_up: string | null;
  runner_up_slug: string | null;
};

export type WMostDecorated = {
  cur_name: string;
  slug: string;
  champion_count: number;
  finals_count: number;
  finals_lost: number;
  last_won: number | null;
  last_final: number | null;
  metro_slug: string | null;
};

export type WCurrent =
  | { year: number; decided: true; champion: string; champion_slug: string; runner_up: string | null; runner_up_slug: string | null; score: string | null }
  | { year: number; decided: false };

export type WCompetition = {
  slug: string;
  label: string;
  short_label: string;
  kind: "cup" | "league";
  region: string;
  country: string;
  active: boolean;
  notes: string;
  year_min: number | null;
  year_max: number | null;
  editions: number;
  champions: WChampion[];
  most_decorated: WMostDecorated[];
  current: WCurrent | null;
};

export type WHonor = {
  competition_slug: string;
  competition_label: string;
  kind: "cup" | "league";
  region: string;
  titles: number;
  runner_ups: number;
  title_years: number[];
  runner_up_years: number[];
};

export type WClub = {
  slug: string;
  name: string;
  metro_slug: string | null;
  metro: string | null;
  country: string | null;
  current_league: string | null;   // NWSL / WSL / Liga F if the club is a current top-flight side
  total_titles: number;
  total_finals: number;
  first_title: number | null;
  last_title: number | null;
  honors: WHonor[];
};

export type WMeta = {
  competitions: number;
  clubs: number;
  clubs_with_metro: number;
  latest_year: number | null;
};

type WData = { meta: WMeta; competitions: WCompetition[]; clubs: WClub[] };

// ─── Data loading (cached) ────────────────────────────────────────────────────

let _cache: WData | null = null;
function loadData(): WData {
  if (_cache) return _cache;
  const file = join(process.cwd(), "public", "data", "football", "womens-football.json");
  _cache = JSON.parse(readFileSync(file, "utf8")) as WData;
  return _cache;
}

// ─── Public helpers ───────────────────────────────────────────────────────────

export function getWMeta(): WMeta {
  return loadData().meta;
}

export function getWCompetitions(): WCompetition[] {
  return loadData().competitions;
}

export function getAllWCompetitionSlugs(): string[] {
  return loadData().competitions.map((c) => c.slug);
}

export function getWCompetition(slug: string): WCompetition | null {
  return loadData().competitions.find((c) => c.slug === slug) ?? null;
}

export function getWClubs(): WClub[] {
  return loadData().clubs;
}

export function getAllWClubSlugs(): string[] {
  return loadData().clubs.map((c) => c.slug);
}

export function getWClub(slug: string): WClub | null {
  return loadData().clubs.find((c) => c.slug === slug) ?? null;
}

// Latest decided champion per competition, in hub display order.
export function getWCurrentChampions(): { competition: WCompetition; current: WCurrent }[] {
  return loadData()
    .competitions
    .filter((c) => c.current !== null)
    .map((c) => ({ competition: c, current: c.current as WCurrent }));
}

// ─── Club identity helpers ────────────────────────────────────────────────────

const STOP = new Set([
  "women", "womens", "ladies", "feminin", "feminines", "feminine",
  "femenino", "femenina", "femeni", "femenil", "frauen", "feminil",
  "fc", "cf", "sc", "afc", "ac", "club", "the", "lfc", "wfc", "fk", "sk",
]);

function normName(s: string): string {
  if (!s) return "";
  const stripped = s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/\(.*?\)/g, " ")
    .replace(/[^a-z0-9]+/g, " ");
  return stripped
    .split(" ")
    .filter((t) => t && !STOP.has(t))
    .join("");
}

// Resolve a W Football marker / display name to a portal club page, used by
// lib/teamLinks so NWSL / WSL map markers and metro rosters deep-link in.
// Only clubs present in the honors data (i.e. title or final winners) have a
// page, so non-decorated current clubs correctly return null.
// ESPN / broadcast display names that do not normalize to the canonical
// club name (e.g. ESPN's "Gotham FC" or "Seattle Reign FC"). Maps
// normName(alias) -> canonical club slug so live NWSL standings rows
// deep-link to the correct club page.
const W_CLUB_NAME_ALIASES: Record<string, string> = {
  gotham: "nj-ny-gotham-fc",
  seattlereign: "ol-reign",
};

let _nameIndex: Map<string, WClub> | null = null;
export function getWClubByName(name: string): WClub | null {
  if (!name) return null;
  if (!_nameIndex) {
    _nameIndex = new Map();
    for (const c of loadData().clubs) {
      const k = normName(c.name);
      if (k && !_nameIndex.has(k)) _nameIndex.set(k, c);
    }
  }
  const key = normName(name);
  const direct = _nameIndex.get(key);
  if (direct) return direct;
  const aliasSlug = W_CLUB_NAME_ALIASES[key];
  if (aliasSlug) return getWClub(aliasSlug);
  return null;
}

// Deterministic monogram (initials + color) for clubs lacking a crest asset.
const PALETTE = [
  "#7c3aed", "#0ea5e9", "#dc2626", "#059669", "#d97706",
  "#db2777", "#2563eb", "#ca8a04", "#0d9488", "#9333ea",
];

export function wMonogram(club: { slug: string; name: string }): { mono: string; bg: string; fg: string } {
  const words = club.name
    .replace(/\(.*?\)/g, " ")
    .split(/[^A-Za-zÀ-ÿ0-9]+/)
    .filter((w) => w && !STOP.has(w.toLowerCase()));
  const mono = (words.slice(0, 2).map((w) => w[0]).join("") || club.name.slice(0, 2)).toUpperCase();
  let h = 0;
  for (let i = 0; i < club.slug.length; i++) h = (h * 31 + club.slug.charCodeAt(i)) >>> 0;
  return { mono, bg: PALETTE[h % PALETTE.length], fg: "#FFFFFF" };
}


// ─── Hub grouping (mirrors the men's Club Football home page) ──────────────────
// "European & world tournament hubs" = competitions whose region is Europe or
// global. "League hubs" = the remaining competitions grouped by country, so each
// country hub carries every competition that falls under it.

const TOURNAMENT_REGIONS = new Set(["Europe", "Global"]);

const REGION_HUBS: { slug: string; country: string }[] = [
  { slug: "england", country: "England" },
  { slug: "united-states", country: "United States" },
  { slug: "spain", country: "Spain" },
];

export type WLeagueHubClub = {
  slug: string;
  name: string;
  titles: number;
  finals: number;
  last_title: number | null;
  metro_slug: string | null;
  metro: string | null;
};

export type WLeagueHub = {
  slug: string;
  country: string;
  competitions: WCompetition[];
  most_decorated: WLeagueHubClub[];
};

// Tournament competitions (UWCL, FIFA Women's Champions Cup), in hub order.
export function getWTournamentCompetitions(): WCompetition[] {
  return loadData().competitions.filter((c) => TOURNAMENT_REGIONS.has(c.region));
}

export function getAllWLeagueHubSlugs(): string[] {
  return REGION_HUBS.map((r) => r.slug);
}

function buildLeagueHub(slug: string, country: string): WLeagueHub {
  const comps = loadData().competitions.filter((c) => c.region === country);
  const compSlugs = new Set(comps.map((c) => c.slug));
  const out: WLeagueHubClub[] = [];
  for (const club of loadData().clubs) {
    let titles = 0;
    let finals = 0;
    let last: number | null = null;
    for (const h of club.honors) {
      if (!compSlugs.has(h.competition_slug)) continue;
      titles += h.titles;
      finals += h.titles + h.runner_ups;
      const ly = h.title_years.length ? Math.max(...h.title_years) : null;
      if (ly !== null) last = last === null ? ly : Math.max(last, ly);
    }
    if (finals > 0) {
      out.push({ slug: club.slug, name: club.name, titles, finals, last_title: last, metro_slug: club.metro_slug, metro: club.metro });
    }
  }
  out.sort((a, b) => b.titles - a.titles || b.finals - a.finals || a.name.localeCompare(b.name));
  return { slug, country, competitions: comps, most_decorated: out };
}

export function getWLeagueHubs(): WLeagueHub[] {
  return REGION_HUBS.map((r) => buildLeagueHub(r.slug, r.country));
}

export function getWLeagueHub(slug: string): WLeagueHub | null {
  const r = REGION_HUBS.find((x) => x.slug === slug);
  return r ? buildLeagueHub(r.slug, r.country) : null;
}


// ─── Decorated-club rows (shared by the sortable Most Decorated tables) ────────
// Per-club honors breakdown used by the home page and the league hub tables.
// total_titles/total_finals are carried for the default ranking even though
// they are not shown as their own columns.

export type WDecoratedRow = {
  slug: string;
  name: string;
  country: string | null;
  metro: string | null;
  metro_slug: string | null;
  leagueTitles: number;   // top-flight league titles (WSL, Liga F, NWSL Championship)
  faCups: number;         // Women's FA Cup wins
  faCupFinals: number;    // Women's FA Cup final appearances
  wclChamps: number;      // UEFA Women's Champions League titles
  wclFinals: number;      // UEFA Women's Champions League final appearances
  nwslChampionship: number; // NWSL Championship (playoff final) titles
  nwslShield: number;       // NWSL Shield (regular-season) titles
  total_titles: number;
  total_finals: number;
};

export function decoratedRows(clubs: WClub[]): WDecoratedRow[] {
  return clubs.map((c) => {
    let leagueTitles = 0;
    let faCups = 0;
    let faCupFinals = 0;
    let wclChamps = 0;
    let wclFinals = 0;
    let nwslChampionship = 0;
    let nwslShield = 0;
    for (const h of c.honors) {
      if (h.competition_slug === "wsl" || h.competition_slug === "liga-f" || h.competition_slug === "nwsl-championship") leagueTitles += h.titles;
      if (h.competition_slug === "womens-fa-cup") {
        faCups += h.titles;
        faCupFinals += h.titles + h.runner_ups;
      }
      if (h.competition_slug === "uwcl") {
        wclChamps += h.titles;
        wclFinals += h.titles + h.runner_ups;
      }
      if (h.competition_slug === "nwsl-championship") nwslChampionship += h.titles;
      if (h.competition_slug === "nwsl-shield") nwslShield += h.titles;
    }
    return {
      slug: c.slug,
      name: c.name,
      country: c.country,
      metro: c.metro,
      metro_slug: c.metro_slug,
      leagueTitles,
      faCups,
      faCupFinals,
      wclChamps,
      wclFinals,
      nwslChampionship,
      nwslShield,
      total_titles: c.total_titles,
      total_finals: c.total_finals,
    };
  });
}

// Full club objects for a league hub: every club with at least one final in
// that country's competitions, ordered by total honors.
export function getWLeagueHubClubs(slug: string): WClub[] {
  const r = REGION_HUBS.find((x) => x.slug === slug);
  if (!r) return [];
  const comps = loadData().competitions.filter((c) => c.region === r.country);
  const cs = new Set(comps.map((c) => c.slug));
  return loadData()
    .clubs
    .filter((club) => club.honors.some((h) => cs.has(h.competition_slug)));
}


// ─── Column configuration for the sortable Most Decorated tables ───────────────
// Different hubs surface different honors. The home page and the England /
// Spain hubs use the default set; the United States hub swaps the England /
// Europe columns (FA Cup, WCL) for the two NWSL trophies, where "League Titles"
// is the NWSL Championship and "NWSL Shield" is the regular-season title.

export type WStatField =
  | "leagueTitles"
  | "faCups"
  | "faCupFinals"
  | "wclChamps"
  | "wclFinals"
  | "nwslChampionship"
  | "nwslShield";

export type WColumn = { field: WStatField; label: string };

export const WCOLS_DEFAULT: WColumn[] = [
  { field: "leagueTitles", label: "League Titles" },
  { field: "faCups", label: "FA Cups" },
  { field: "faCupFinals", label: "FA Cup Finals" },
  { field: "wclChamps", label: "WCL Champs" },
  { field: "wclFinals", label: "WCL Finals" },
];

export const WCOLS_US: WColumn[] = [
  { field: "nwslChampionship", label: "League Titles" },
  { field: "nwslShield", label: "NWSL Shield" },
];

// Column set for a given league hub slug.
export function columnsForHub(slug: string): WColumn[] {
  return slug === "united-states" ? WCOLS_US : WCOLS_DEFAULT;
}
