import "server-only";
import { readFileSync } from "fs";
import { join } from "path";

// Women's national-team data (FIFA Women's World Cup). Generated by
// scripts/build-wfootball-data.py from the "Int Tournaments" sheet of the
// men's football workbook. Server-only; listed in
// scripts/check-client-imports.mjs. Client components import types only.

export type WWCEdition = {
  year: number;
  host: string | null;
  champion: string | null;
  champion_slug: string | null;
  runner_up: string | null;
  runner_up_slug: string | null;
  third: string | null;
  third_slug: string | null;
  fourth: string | null;
  fourth_slug: string | null;
  final_score: string | null;
};

export type WWCResult = {
  year: number;
  host: string | null;
  finish: string;
  rank: number;
  final_score: string | null;
};

export type WWCNation = {
  slug: string;
  name: string;
  continent: string | null;
  appearances: number;
  titles: number;
  title_years: number[];
  finals: number;
  final_years: number[];
  best_rank: number;
  best_finish: string | null;
  first_appearance: number | null;
  last_appearance: number | null;
  results: WWCResult[];
};

export type WWCMeta = {
  label: string;
  slug: string;
  editions: number;
  nations: number;
  year_min: number | null;
  year_max: number | null;
};

type WWCData = { meta: WWCMeta; editions: WWCEdition[]; nations: WWCNation[] };

let _cache: WWCData | null = null;
function loadData(): WWCData {
  if (_cache) return _cache;
  const file = join(process.cwd(), "public", "data", "football", "womens-world-cup.json");
  _cache = JSON.parse(readFileSync(file, "utf8")) as WWCData;
  return _cache;
}

export function getWWCMeta(): WWCMeta {
  return loadData().meta;
}
export function getWWCEditions(): WWCEdition[] {
  return loadData().editions;
}
export function getWWCNations(): WWCNation[] {
  return loadData().nations;
}
export function getAllWWCNationSlugs(): string[] {
  return loadData().nations.map((n) => n.slug);
}
export function getWWCNation(slug: string): WWCNation | null {
  return loadData().nations.find((n) => n.slug === slug) ?? null;
}
