import "server-only";
import { readFileSync } from "fs";
import { join } from "path";

// WNBA hub data. Generated by scripts/build-wnba-data.py from the WNBA sheet of
// OtherLeagues.xlsx. Franchises fold relocations/renames via the workbook's
// Canonical Name column; current vs defunct comes from the sheet's two lists.

export type WnbaFranchise = {
  slug: string;
  name: string;
  abbr: string;
  city: string | null;
  state: string | null;
  metro_slug: string | null;
  color: string;
  active: boolean;
  defunct: boolean;
  seasons: number;
  w: number;
  l: number;
  win_pct: number | null;
  playoff_appearances: number;
  division_titles: number;
  semifinals: number;
  finals: number;          // finals (championship-series) appearances
  titles: number;
  title_years: number[];
  final_years: number[];
  last_title: number | null;
  first_season: number | null;
  last_season: number | null;
  aka: string[];
};

export type WnbaSeason = {
  year: number;
  team: string;            // name used that season
  canonical: string;
  slug: string;
  conference: string | null;
  w: number;
  l: number;
  win_pct: number | null;
  gb: number | string | null;
  ps_g: number | null;
  pf_g: number | null;
  playoffs: boolean;
  div_title: boolean;
  p_wins: number;
  p_losses: number;
  sf_app: boolean;
  finals_app: boolean;
  champion: boolean;
  finish: string;          // Champion | Runner-up | Semifinals | Playoffs | Missed playoffs
  finish_rank: number;
};

export type WnbaChampion = { year: number; champion: string; champion_slug: string };

export type WnbaMeta = {
  league: string;
  sport: string;
  founded: number;
  latest_season: number;
  total_seasons: number;
  active_count: number;
  defunct_count: number;
};

type WnbaData = { meta: WnbaMeta; franchises: WnbaFranchise[]; seasons: WnbaSeason[]; champions: WnbaChampion[] };

let _cache: WnbaData | null = null;
function loadData(): WnbaData {
  if (_cache) return _cache;
  const file = join(process.cwd(), "public", "data", "wnba", "data.json");
  _cache = JSON.parse(readFileSync(file, "utf8")) as WnbaData;
  return _cache;
}

export function getWnbaMeta(): WnbaMeta { return loadData().meta; }
export function getAllFranchises(): WnbaFranchise[] { return loadData().franchises; }
export function getActiveFranchises(): WnbaFranchise[] { return loadData().franchises.filter((f) => !f.defunct); }
export function getDefunctFranchises(): WnbaFranchise[] { return loadData().franchises.filter((f) => f.defunct); }
export function getAllFranchiseSlugs(): string[] { return loadData().franchises.map((f) => f.slug); }
export function getFranchiseBySlug(slug: string): WnbaFranchise | null {
  return loadData().franchises.find((f) => f.slug === slug) ?? null;
}
export function getChampions(): WnbaChampion[] { return loadData().champions; }

export function getFranchiseSeasons(slug: string): WnbaSeason[] {
  return loadData().seasons.filter((s) => s.slug === slug).sort((a, b) => b.year - a.year);
}

// Latest-season standings, split by conference, each sorted by win%.
export function getLatestStandings(): { conference: string; rows: WnbaSeason[] }[] {
  const d = loadData();
  const yr = d.meta.latest_season;
  const rows = d.seasons.filter((s) => s.year === yr);
  const byConf = new Map<string, WnbaSeason[]>();
  for (const r of rows) {
    const c = r.conference || "League";
    if (!byConf.has(c)) byConf.set(c, []);
    byConf.get(c)!.push(r);
  }
  return [...byConf.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([conference, list]) => ({
      conference,
      rows: list.sort((a, b) => (b.win_pct ?? 0) - (a.win_pct ?? 0) || b.w - a.w),
    }));
}

export function monogramFor(f: WnbaFranchise): { abbr: string; color: string } {
  return { abbr: f.abbr, color: f.color };
}

// teamLinks resolver: match a W Basketball marker name to its franchise,
// including historical (aka) names.
let _nameIndex: Map<string, WnbaFranchise> | null = null;
export function getWnbaFranchiseByTeamName(name: string): WnbaFranchise | null {
  if (!name) return null;
  if (!_nameIndex) {
    _nameIndex = new Map();
    for (const f of loadData().franchises) {
      _nameIndex.set(f.name.toLowerCase(), f);
      for (const a of f.aka) _nameIndex.set(a.toLowerCase(), f);
    }
  }
  return _nameIndex.get(name.trim().toLowerCase()) ?? null;
}
