# -*- coding: utf-8 -*-
"""Sponsor / historical name -> canonical club name.

Canonical names are the EuroLeague hub's own club names
(public/data/basketball/euroleague.json) wherever the club appears there, so
the two pages name the same club the same way. Clubs that never played in the
EuroLeague keep the plain Wikipedia canonical form.

Keys are matched case-insensitively after stripping footnote markers, dagger
symbols and title counters.
"""

ALIASES = {
    # ---------------- Italy: sponsor names dominate the source ------------
    "mobilgirgi varese": "Pallacanestro Varese",
    "ignis varese": "Pallacanestro Varese",
    "varese roosters": "Pallacanestro Varese",
    "antifurti ranger varese": "Pallacanestro Varese",
    "varese": "Pallacanestro Varese",
    "sinudyne bologna": "Virtus Bologna",
    "granarolo bologna": "Virtus Bologna",
    "knorr bologna": "Virtus Bologna",
    "buckler beer bologna": "Virtus Bologna",
    "kinder bologna": "Virtus Bologna",
    "skipper bologna": "Virtus Bologna",
    "vidivici bologna": "Virtus Bologna",
    "virtus segafredo bologna": "Virtus Bologna",
    "minganti bologna": "Virtus Bologna",
    "teamsystem bologna": "Fortitudo Bologna",
    "paf wennington bologna": "Fortitudo Bologna",
    "climamio bologna": "Fortitudo Bologna",
    "billy milano": "Olimpia Milano",
    "simac milano": "Olimpia Milano",
    "tracer milano": "Olimpia Milano",
    "philips milano": "Olimpia Milano",
    "stefanel milano": "Olimpia Milano",
    "armani jeans milano": "Olimpia Milano",
    "ea7 emporio armani milano": "Olimpia Milano",
    "ax armani exchange milano": "Olimpia Milano",
    "simmenthal milano": "Olimpia Milano",
    "borletti milano": "Olimpia Milano",
    "squibb cantu": "Pallacanestro Cantù",
    "gabetti cantu": "Pallacanestro Cantù",
    "bennet cantu": "Pallacanestro Cantù",
    "oransoda cantu": "Pallacanestro Cantù",
    "birra forst cantu": "Pallacanestro Cantù",
    "cantu": "Pallacanestro Cantù",
    "banco roma": "Virtus Roma",
    "banco di roma": "Virtus Roma",
    "lottomatica roma": "Virtus Roma",
    "acea roma": "Virtus Roma",
    "scavolini pesaro": "Victoria Libertas",
    "mobilgirgi caserta": "JuveCaserta Basket",
    "phonola caserta": "JuveCaserta Basket",
    "juvecaserta": "JuveCaserta Basket",
    "montepaschi siena": "Mens Sana Basketball Siena",
    "mens sana": "Mens Sana Basketball Siena",
    "mens sana 1871": "Mens Sana Basketball Siena",
    "benetton treviso": "Benetton Treviso",
    "treviso": "Benetton Treviso",
    "umana reyer venezia": "Reyer Venezia",
    "banco di sardegna sassari": "Dinamo Sassari",
    "grissin bon reggio emilia": "Pallacanestro Reggiana",
    "reggiana": "Pallacanestro Reggiana",
    "dolomiti energia trento": "Aquila Basket Trento",
    "trento": "Aquila Basket Trento",
    "germani brescia": "Pallacanestro Brescia",
    "enichem livorno": "Libertas Livorno",
    "libertas liburnia": "Libertas Livorno",
    "ginnastica triestina": "Pallacanestro Trieste",
    "olimpia milano": "Olimpia Milano",
    "virtus bologna": "Virtus Bologna",
    "fortitudo bologna": "Fortitudo Bologna",
    "victoria libertas": "Victoria Libertas",
    "virtus roma": "Virtus Roma",
    "dinamo sassari": "Dinamo Sassari",
    "reyer venezia": "Reyer Venezia",

    # ---------------- Spain -----------------------------------------------
    "real madrid c.f.": "Real Madrid Baloncesto",
    "real madrid": "Real Madrid Baloncesto",
    "real madrid teka": "Real Madrid Baloncesto",
    "real madrid asegurator": "Real Madrid Baloncesto",
    "c.f. barcelona": "FC Barcelona Basquet",
    "f.c. barcelona": "FC Barcelona Basquet",
    "fc barcelona": "FC Barcelona Basquet",
    "barcelona": "FC Barcelona Basquet",
    "fc barcelona banca catalana": "FC Barcelona Basquet",
    "winterthur fc barcelona": "FC Barcelona Basquet",
    "axa fc barcelona": "FC Barcelona Basquet",
    "regal fc barcelona": "FC Barcelona Basquet",
    "fc barcelona regal": "FC Barcelona Basquet",
    "fc barcelona lassa": "FC Barcelona Basquet",
    "barcelona lassa": "FC Barcelona Basquet",
    "club juventud badalona": "Joventut Badalona",
    "ron negrita joventut": "Joventut Badalona",
    "ram joventut badalona": "Joventut Badalona",
    "montigala joventut": "Joventut Badalona",
    "marbella joventut": "Joventut Badalona",
    "joventut": "Joventut Badalona",
    "tau ceramica": "Saski Baskonia",
    "caja laboral": "Saski Baskonia",
    "kirolbet baskonia": "Saski Baskonia",
    "baskonia": "Saski Baskonia",
    "s.d. kas vitoria": "Saski Baskonia",
    "unicaja": "Unicaja Málaga",
    "caja san fernando": "Real Betis Baloncesto",
    "malaga": "Unicaja Málaga",
    "tdk manresa": "Bàsquet Manresa",
    "manresa": "Bàsquet Manresa",
    "c.d. manresa": "Bàsquet Manresa",
    "pamesa valencia": "Valencia Basket",
    "valencia": "Valencia Basket",
    "adecco estudiantes": "CB Estudiantes",
    "estudiantes madrid": "CB Estudiantes",
    "estudiantes": "CB Estudiantes",
    "bizkaia bilbao basket": "Bilbao Basket",
    "bilbao": "Bilbao Basket",
    "ucam murcia": "UCAM Murcia",
    "picadero j.c. barcelona": "Picadero JC",
    "picadero": "Picadero JC",
    "orillo verde sabadell": "Orillo Verde Sabadell",
    "orillo verde": "Orillo Verde Sabadell",

    # ---------------- Turkey ----------------------------------------------
    "galatasaray": "Galatasaray Basketball",
    "galatasaray medical park": "Galatasaray Basketball",
    "fenerbahce": "Fenerbahçe Basketball",
    "fenerbahce ulker": "Fenerbahçe Basketball",
    "fenerbahce dogus": "Fenerbahçe Basketball",
    "fenerbahce beko": "Fenerbahçe Basketball",
    "efes pilsen": "Anadolu Efes",
    "anadolu efes": "Anadolu Efes",
    "eczacibasi": "Eczacıbaşı SK",
    "besiktas": "Beşiktaş Basketbol",
    "besiktas milangaz": "Beşiktaş Basketbol",
    "karsiyaka": "Karşıyaka Basket",
    "pinar karsiyaka": "Karşıyaka Basket",
    "tofas": "Tofaş SK",
    "ulker": "Ülker",
    "darussafaka": "Daçka Basketbol",
    "turk telekom": "Türk Telekom BK",

    # ---------------- France ----------------------------------------------
    "asvel": "ASVEL Basket",
    "ldlc asvel": "ASVEL Basket",
    "limoges csp": "Limoges CSP",
    "pau-orthez": "Élan Béarnais",
    "pau-lacq-orthez": "Élan Béarnais",
    "orthez": "Élan Béarnais",
    "as monaco": "AS Monaco Basket",
    "monaco": "AS Monaco Basket",
    "paris basketball": "Paris Basketball",
    "psg racing": "Paris Basket Racing",
    "racing club de france": "Paris Basket Racing",
    "racing paris": "Paris Basket Racing",
    "metropolitans 92": "Metropolitans 92",
    "le mans sarthe": "Le Mans Sarthe Basket",
    "le mans": "Le Mans Sarthe Basket",
    "moderne": "Le Mans Sarthe Basket",
    "sig": "SIG Strasbourg",
    "sig strasbourg": "SIG Strasbourg",
    "sluc nancy": "SLUC Nancy Basket",
    "elan chalon": "Élan Chalon",
    "chorale roanne": "Chorale Roanne",
    "chorale mulsant": "Chorale Roanne",
    "cholet": "Cholet Basket",
    "jsf nanterre": "Nanterre 92",
    "nanterre 92": "Nanterre 92",
    "olympique antibes": "Olympique Antibes",
    "entente orleanaise loiret": "Orléans Loiret Basket",
    "bcm gravelines": "BCM Gravelines",
    "jda dijon": "JDA Dijon",
    "icam lille": "ICAM Lille",
    "lille": "ICAM Lille",
    "marseille": "Union athlétique de Marseille",
    "union athletique de marseille": "Union athlétique de Marseille",

    # ---------------- Lithuania -------------------------------------------
    "zalgiris": "BC Žalgiris",
    "zalgiris kaunas": "BC Žalgiris",
    "rytas": "BC Rytas",
    "lietuvos rytas": "BC Rytas",
    "statyba": "BC Rytas",
    "neptunas": "Neptūnas Klaipėda",
    "lietkabelis": "BC Lietkabelis",
    "juventus": "BC Juventus",
    "siauliai": "BC Šiauliai",
    "atletas": "BC Atletas",
    "olimpas": "BC Olimpas",
    "sakalai": "BC Sakalai",

    # ---------------- Israel ----------------------------------------------
    "maccabi tel aviv": "Maccabi Tel Aviv BC",
    "maccabi elite tel aviv": "Maccabi Tel Aviv BC",
    "maccabi electra tel aviv": "Maccabi Tel Aviv BC",
    "hapoel tel aviv": "Hapoel Tel Aviv BC",
    "hapoel jerusalem": "Hapoel Jerusalem BC",
    "hapoel galil elyon": "Hapoel Galil Elyon BC",
    "hapoel gilboa galil": "Hapoel Gilboa Galil",
    "gilboa/galil": "Hapoel Gilboa Galil",
    "maccabi rishon lezion": "Maccabi Rishon LeZion BC",
    "maccabi ra'anana": "Maccabi Ra'anana BC",
    "maccabi ironi ra'anana": "Maccabi Ra'anana BC",
    "hapoel holon": "Hapoel Holon",
    "maccabi haifa": "Maccabi Haifa BC",
    "hapoel haifa": "Hapoel Haifa BC",
    "hapoel eilat": "Hapoel Eilat",
    "bnei herzliya": "Bnei Herzliya",
    "maccabi ashdod": "Maccabi Ashdod",
    "ironi ramat gan": "Ironi Ramat Gan",
    "hapoel ramat gan": "Hapoel Ramat Gan",
    "ironi nahariya": "Ironi Nahariya",
    "ironi naharia": "Ironi Nahariya",
    "maccabi elitzur netanya": "Elitzur Netanya",
    "elitzur netanya": "Elitzur Netanya",
    "hapoel gvat/yagur": "Hapoel Gvat/Yagur",

    # ---------------- Russia / Soviet -------------------------------------
    "cska moscow": "PBC CSKA Moscow",
    "unics": "BC UNICS Kazan",
    "khimki": "BC Khimki",
    "zenit saint petersburg": "BC Zenit Saint Petersburg",
    "bc zenit saint petersburg": "BC Zenit Saint Petersburg",
    "ural great perm": "Ural Great Perm",
    "spartak saint petersburg": "BC Spartak Saint Petersburg",
    "spartak leningrad": "BC Spartak Saint Petersburg",
    "dynamo moscow": "MBC Dynamo Moscow",
    "lokomotiv-kuban": "PBC Lokomotiv Kuban",
    "lokomotiv kuban": "PBC Lokomotiv Kuban",
    "nizhny novgorod": "BC Nizhny Novgorod",
    "avtodor saratov": "BC Avtodor",
    "bc samara": "BC Samara",
    "stroitel samara": "BC Samara",
    "csk vvs samara": "BC Samara",
    "rigas ask": "Rīgas ASK",
    "budivelnyk kyiv": "BC Budivelnyk",
    "kalev tallinn": "BC Kalev",
    "dinamo tbilisi": "BC Dinamo Tbilisi",
    "zalgiris kaunas ": "BC Žalgiris",

    # ---------------- Adriatic / Yugoslavia -------------------------------
    "partizan": "KK Partizan",
    "partizan igokea": "KK Partizan",
    "partizan mt:s": "KK Partizan",
    "partizan mts": "KK Partizan",
    "partizan nis": "KK Partizan",
    "partizan pivara mb": "KK Partizan",
    "partizan mozzart bet": "KK Partizan",
    "crvena zvezda": "KK Crvena zvezda",
    "crvena zvezda telekom": "KK Crvena zvezda",
    "crvena zvezda mts": "KK Crvena zvezda",
    "crvena zvezda meridianbet": "KK Crvena zvezda",
    "cibona": "KK Cibona",
    "cibona vip": "KK Cibona",
    "zadar": "KK Zadar",
    "cedevita": "KK Cedevita Junior",
    "cedevita olimpija": "KK Cedevita Olimpija",
    "union olimpija": "KK Cedevita Olimpija",
    "ask olimpija": "KK Cedevita Olimpija",
    "krka": "KK Krka",
    "pivovarna lasko": "Pivovarna Laško BC",
    "buducnost m:tel": "KK Budućnost",
    "buducnost voli": "KK Budućnost",
    "buducnost": "KK Budućnost",
    "hemofarm": "KK Vršac",
    "reflex": "KK FMP",
    "fmp": "KK FMP",
    "mega leks": "KK Mega Basket",
    "mega mis": "KK Mega Basket",
    "igokea": "KK Igokea",
    "mornar": "KK Mornar Bar",
    "radnicki kragujevac": "KK Radnički Kragujevac",
    "dubai basketball": "Dubai Basketball",
    "jugoplastika": "KK Split",
    "pop 84": "KK Split",
    "bosna": "KK Bosna",
    "sibenka": "KK Šibenik",
    "okk beograd": "OKK Beograd",
    "radnicki belgrade": "KK Radnički Belgrade",
    "proleter zrenjanin": "KK Proleter Zrenjanin",
    "yugoslav army": "Yugoslav Army",

    # ---------------- Greece ----------------------------------------------
    "panathinaikos": "Panathinaikos BC",
    "olympiacos": "Olympiacos BC",
    "aris": "Aris BC",
    "aek": "AEK BC",
    "paok": "PAOK BC",
    "panellinios": "Panellinios BC",
    "iraklis": "Iraklis BC",
    "panionios": "Panionios BC",
    "maroussi": "Maroussi BC",
    "promitheas": "Promitheas Patras",
    "promitheas patras": "Promitheas Patras",
    "lavrio": "Lavrio BC",
    "near east": "Near East",
    "athens university": "Athens University",
}
