import type { Metadata } from "next";
import Link from "next/link";
import { getRefreshSchedule } from "@/lib/refreshSchedule";
import ScheduleCalendar from "./ScheduleCalendar";

// Regenerated by mac-mini-jobs/export_schedule.py after every dispatcher tick
// (~every 10 minutes) -- see lib/refreshSchedule.ts.
//
// force-dynamic, not ISR. This page was previously `revalidate = 600` while
// getRefreshSchedule() inherited loadLiveJson's 3600s Data Cache default, so
// five of every six route revalidations re-rendered identical hour-old JSON
// and the page looked frozen. Rather than chase two windows into agreement,
// the page is rendered per request: it is unlisted, noindex, and gets a
// handful of views a day, so there is no cache to protect. The freshness
// floor is now GitHub raw's own ~5-minute CDN TTL.
export const dynamic = "force-dynamic";

// Unlisted on purpose: not in DesktopNav/MobileMenu, not in app/sitemap.ts,
// matching the existing /activity precedent. Reachable by direct URL only.
export const metadata: Metadata = {
  title: "Data Refresh Schedule",
  description: "When each automated data job on the Mac mini is scheduled to run.",
  robots: { index: false, follow: false },
};

const MONO = { fontFamily: "'JetBrains Mono', monospace" } as const;

export default async function RefreshSchedulePage() {
  const schedule = await getRefreshSchedule();
  const jobs = schedule?.jobs ?? [];

  return (
    <main className="min-h-screen pt-8 pb-24 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto">
        <nav className="text-xs mb-8" aria-label="Breadcrumb">
          <Link
            href="/"
            className="text-[var(--text-muted)] hover:text-[var(--accent)] transition-colors"
            style={MONO}
          >
            &larr; Back to rankings
          </Link>
        </nav>

        <header className="mb-10 border-b border-[var(--border)] pb-10">
          <p className="text-xs tracking-widest text-[var(--text-muted)] mb-3" style={MONO}>
            DATA REFRESH SCHEDULE
          </p>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            What refreshes, and when.
          </h1>
          <p className="text-lg text-[var(--text-muted)] leading-relaxed">
            Every automated data job running on the Mac mini, generated directly
            from its own schedule file. Times are UTC on the mini, converted
            below to your local time.
          </p>
          {schedule?.generated_at && (
            <p className="mt-4 text-xs text-[var(--text-muted)]" style={MONO}>
              {jobs.length} jobs · schedule last regenerated{" "}
              {new Date(schedule.generated_at).toLocaleString(undefined, {
                dateStyle: "medium",
                timeStyle: "short",
              })}
            </p>
          )}
        </header>

        {jobs.length === 0 ? (
          <p className="text-[var(--text-muted)]">
            The schedule export hasn&rsquo;t landed yet. Check back shortly.
          </p>
        ) : (
          <ScheduleCalendar jobs={jobs} />
        )}
      </div>
    </main>
  );
}
