#!/usr/bin/env python3
"""Emit lib/championStatus.generated.ts from league playoff-state.json.

Time-boxed champion banners for the Sports nav dropdown and the League Hub
sidebar (consumed by lib/leagueStatus.tsx). When a league's postseason
completes and a champion is crowned, that league's nav tag shows
"<Champion> - <Trophy>" instead of "Live - Playoffs", then falls back to
Offseason after a cutoff:

  - NBA: a FIXED cutoff (2026-06-22, end of day UTC) per editorial request.
  - NHL: a ~9-DAY window. The cutoff is stamped the first time the champion is
    detected and then preserved across rebuilds (read back from the existing
    generated file) so repeated rebuilds do not slide the window.

A league with no crowned champion emits no entry, so leagueStatus.tsx falls
through to its normal status (e.g. "Live - Playoffs"). Run AFTER
build-nba-data.py / build-nhl-data.py; wired into run-workbook-sync.py.
"""
import datetime
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA = REPO_ROOT / "public" / "data"
OUT = REPO_ROOT / "lib" / "championStatus.generated.ts"


def _ms(y, mo, d, h=23, mi=59, s=59):
    return int(datetime.datetime(y, mo, d, h, mi, s,
                                 tzinfo=datetime.timezone.utc).timestamp() * 1000)


# trophy = label suffix; exactly one of fixed_until / window_days per league.
LEAGUES = [
    {"page": "/teams/nba", "data": "nba",
     "trophy": "NBA Champions", "fixed_until": _ms(2026, 6, 22)},
    {"page": "/teams/nhl", "data": "nhl",
     "trophy": "Stanley Cup Champions", "window_days": 9},
]


def load_state(name):
    p = DATA / name / "playoff-state.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def champion_of(state):
    """Return the crowned champion's display key, or None. Gated on the
    postseason being complete so an in-progress final never crowns a team."""
    if not state or not state.get("is_postseason_complete"):
        return None
    for team, info in (state.get("by_franchise") or {}).items():
        if info.get("state") == "champion":
            return team
    return None


def existing_until(page, label):
    """Reuse a previously-stamped cutoff for the same page+label so a
    re-run does not slide a window-based banner."""
    if not OUT.exists():
        return None
    txt = OUT.read_text(encoding="utf-8")
    m = re.search(r'"%s":\s*\{\s*label:\s*"([^"]*)",\s*until:\s*(\d+)'
                  % re.escape(page), txt)
    if m and m.group(1) == label:
        return int(m.group(2))
    return None


def main():
    now_ms = int(datetime.datetime.now(datetime.timezone.utc).timestamp() * 1000)
    entries = {}
    for lg in LEAGUES:
        champ = champion_of(load_state(lg["data"]))
        if not champ:
            continue
        label = f"{champ} - {lg['trophy']}"
        if "fixed_until" in lg:
            until = lg["fixed_until"]
        else:
            until = existing_until(lg["page"], label) or (
                now_ms + lg["window_days"] * 86400 * 1000)
        entries[lg["page"]] = (label, until)

    lines = [
        "// AUTO-GENERATED by scripts/emit-champion-status.py - do not edit by hand.",
        "// Time-boxed champion banners for the Sports nav + League Hub sidebar.",
        "// Regenerated by run-workbook-sync.py after the league data builds.",
        "export type ChampionBanner = { label: string; until: number };",
        "export const CHAMPION_STATUS: Record<string, ChampionBanner> = {",
    ]
    for page, (label, until) in entries.items():
        lines.append(f'  "{page}": {{ label: "{label}", until: {until} }},')
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO_ROOT)} with {len(entries)} "
          f"champion banner(s): " + (", ".join(entries.keys()) or "none"))


if __name__ == "__main__":
    main()
