"use client";

import { useRef, useState, type ReactNode } from "react";

// Per-club power-ranking history for /teams/football/[slug]. Two stacked panels
// (rank, then score) sharing one season axis — one metric per axis. Segments are
// drawn ONLY between consecutive seasons, so a top-flight gap (relegation) leaves
// a break rather than a misleading straight line. Data: public/data/football/
// club-history.json, regenerated by scripts/uefa/build_trends.py each new season.

type Pt = { season: string; rank: number; score: number };
const ss = (s: string) => (s.length >= 7 ? `${s.slice(2, 4)}/${s.slice(5, 7)}` : s);
const seasonLabel = (y: number) => `${y}-${String((y + 1) % 100).padStart(2, "0")}`;

export default function ClubHistoryChart({ history }: { history: Pt[] }) {
  const ref = useRef<SVGSVGElement | null>(null);
  const [hi, setHi] = useState<number | null>(null);
  if (!history || history.length === 0) return null;

  const yr = (s: string) => parseInt(s.slice(0, 4), 10);
  const pts = [...history].sort((a, b) => yr(a.season) - yr(b.season));
  const y0 = yr(pts[0].season), y1 = yr(pts[pts.length - 1].season);
  const years: number[] = [];
  for (let y = y0; y <= y1; y++) years.push(y);
  const byYear = new Map<number, Pt>(pts.map((p) => [yr(p.season), p]));
  const maxRank = Math.max(10, ...pts.map((p) => p.rank));
  const maxScore = Math.max(1.4, ...pts.map((p) => p.score));

  const W = 560, PL = 30, PR = 14;
  const single = y1 === y0;
  const px = (y: number) => (single ? (PL + (W - PR)) / 2 : PL + ((y - y0) / (y1 - y0)) * (W - PL - PR));
  const RT = 26, RB = 116, ST = 152, SB = 242, XL = 260, H = 272;
  const rankY = (r: number) => RT + ((r - 1) / (maxRank - 1)) * (RB - RT);
  const scoreY = (s: number) => ST + (1 - s / maxScore) * (SB - ST);

  const seg = (yfn: (p: Pt) => number, key: string): ReactNode[] => {
    const out: ReactNode[] = [];
    for (let y = y0; y < y1; y++) {
      const a = byYear.get(y), b = byYear.get(y + 1);
      if (a && b) out.push(<line key={`${key}${y}`} x1={px(y)} y1={yfn(a)} x2={px(y + 1)} y2={yfn(b)} stroke="var(--accent)" strokeWidth={2} strokeLinecap="round" />);
    }
    return out;
  };
  const dots = (yfn: (p: Pt) => number, key: string): ReactNode[] =>
    pts.map((p) => <circle key={`${key}${p.season}`} cx={px(yr(p.season))} cy={yfn(p)} r={hi === yr(p.season) ? 4.5 : 3} fill="var(--accent)" stroke="var(--bg-card)" strokeWidth={1.4} />);

  function onMove(e: React.MouseEvent<SVGSVGElement>) {
    const r = ref.current?.getBoundingClientRect();
    if (!r || !r.width) return;
    const xv = ((e.clientX - r.left) / r.width) * W;
    let best: number | null = null, bd = Infinity;
    for (const y of years) if (byYear.get(y)) { const d = Math.abs(px(y) - xv); if (d < bd) { bd = d; best = y; } }
    setHi(best);
  }
  const cur = hi != null ? byYear.get(hi) : null;

  return (
    <div>
      <div className="flex items-baseline justify-between gap-3 mb-1">
        <h3 className="text-sm font-semibold">Power-ranking history</h3>
        <div className="text-xs tabular-nums" style={{ minHeight: "1rem" }}>
          {cur ? (
            <span className="text-[var(--text-muted)]"><span className="font-semibold text-[var(--text)]">{ss(cur.season)}</span> — rank <span className="font-semibold text-[var(--text)]">{cur.rank}</span>, score <span className="font-semibold text-[var(--text)]">{cur.score.toFixed(3)}</span></span>
          ) : <span className="text-[var(--text-dim)]">Hover a season for its rank and score</span>}
        </div>
      </div>
      <svg ref={ref} viewBox={`0 0 ${W} ${H}`} className="w-full" role="img" onMouseMove={onMove} onMouseLeave={() => setHi(null)}>
        <text x={PL} y={RT - 12} fontSize={10} fill="var(--text-muted)">Rank (1 = best)</text>
        {[1, maxRank].map((r) => (
          <g key={`rg${r}`}><line x1={PL} x2={W - PR} y1={rankY(r)} y2={rankY(r)} stroke="var(--border)" strokeWidth={1} /><text x={PL - 4} y={rankY(r) + 3} textAnchor="end" fontSize={9} fill="var(--text-dim)">{r}</text></g>
        ))}
        {seg((p) => rankY(p.rank), "r")}
        {dots((p) => rankY(p.rank), "rd")}
        <text x={PL} y={ST - 12} fontSize={10} fill="var(--text-muted)">Score (per-season normalised)</text>
        {[0, 0.5, 1.0].map((s) => (
          <g key={`sg${s}`}><line x1={PL} x2={W - PR} y1={scoreY(s)} y2={scoreY(s)} stroke="var(--border)" strokeWidth={1} /><text x={PL - 4} y={scoreY(s) + 3} textAnchor="end" fontSize={9} fill="var(--text-dim)">{s.toFixed(1)}</text></g>
        ))}
        {seg((p) => scoreY(p.score), "s")}
        {dots((p) => scoreY(p.score), "sd")}
        {years.map((y) => (
          <text key={`x${y}`} x={px(y)} y={XL} textAnchor="middle" fontSize={9} fill={byYear.get(y) ? "var(--text-dim)" : "var(--border)"}>{ss(seasonLabel(y))}</text>
        ))}
        {hi != null && <line x1={px(hi)} x2={px(hi)} y1={RT} y2={SB} stroke="var(--text-dim)" strokeWidth={1} strokeDasharray="3 3" />}
      </svg>
    </div>
  );
}
